// Code generated by tools/gen/main.go. DO NOT EDIT.

package misc

import "context"

// Service provides misc-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new MiscService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// Endpoints calls /endpoints.
func (s *Service) Endpoints(ctx context.Context) ([]string, error) {
	var resp []string
	if err := s.cli.Do(ctx, "/endpoints", nil, &resp); err != nil {
		return *new([]string), err
	}
	return resp, nil
}

