// Code generated by tools/gen/main.go. DO NOT EDIT.

package sw

import "context"

// Service provides sw-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new SwService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// RegisterRequest represents the request body for sw/register.
type RegisterRequest struct {
	Endpoint *string `json:"endpoint"`
	Auth *string `json:"auth"`
	Publickey *string `json:"publickey"`
	SendReadMessage *bool `json:"sendReadMessage,omitempty"`
}

// Register calls /sw/register (authenticated).
func (s *Service) Register(ctx context.Context, req *RegisterRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/sw/register", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UnregisterRequest represents the request body for sw/unregister.
type UnregisterRequest struct {
	Endpoint *string `json:"endpoint"`
}

// Unregister calls /sw/unregister.
func (s *Service) Unregister(ctx context.Context, req *UnregisterRequest) error {
	return s.cli.Do(ctx, "/sw/unregister", req, nil)
}

// ShowRegistrationRequest represents the request body for sw/show-registration.
type ShowRegistrationRequest struct {
	Endpoint *string `json:"endpoint"`
}

// ShowRegistration calls /sw/show-registration (authenticated).
func (s *Service) ShowRegistration(ctx context.Context, req *ShowRegistrationRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/sw/show-registration", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UpdateRegistrationRequest represents the request body for sw/update-registration.
type UpdateRegistrationRequest struct {
	Endpoint *string `json:"endpoint"`
	SendReadMessage *bool `json:"sendReadMessage,omitempty"`
}

// UpdateRegistration calls /sw/update-registration (authenticated).
func (s *Service) UpdateRegistration(ctx context.Context, req *UpdateRegistrationRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/sw/update-registration", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

