// Code generated by tools/gen/main.go. DO NOT EDIT.

package fetch

import "context"

// Service provides fetch-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new FetchService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// FetchRssRequest represents the request body for fetch-rss.
type FetchRssRequest struct {
	Url *string `json:"url"`
}

// FetchRss calls /fetch-rss.
func (s *Service) FetchRss(ctx context.Context, req *FetchRssRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/fetch-rss", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// FetchExternalResourcesRequest represents the request body for fetch-external-resources.
type FetchExternalResourcesRequest struct {
	Url *string `json:"url"`
	Hash *string `json:"hash"`
}

// FetchExternalResources calls /fetch-external-resources (authenticated).
func (s *Service) FetchExternalResources(ctx context.Context, req *FetchExternalResourcesRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/fetch-external-resources", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

