// Code generated by tools/gen/main.go. DO NOT EDIT.

package mute

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides mute-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new MuteService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// DeleteRequest represents the request body for mute/delete.
type DeleteRequest struct {
	UserId *types.ID `json:"userId"`
}

// Delete calls /mute/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/mute/delete", req, nil)
}

// CreateRequest represents the request body for mute/create.
type CreateRequest struct {
	UserId *types.ID `json:"userId"`
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
}

// Create calls /mute/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) error {
	return s.cli.Do(ctx, "/mute/create", req, nil)
}

// ListRequest represents the request body for mute/list.
type ListRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// List calls /mute/list (authenticated).
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/mute/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

