// Code generated by tools/gen/main.go. DO NOT EDIT.

package export

import "context"

// Service provides export-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ExportService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ExportCustomEmojis calls /export-custom-emojis (authenticated).
func (s *Service) ExportCustomEmojis(ctx context.Context) error {
	return s.cli.Do(ctx, "/export-custom-emojis", nil, nil)
}

