// Code generated by tools/gen/main.go. DO NOT EDIT.

package test

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides test-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new TestService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// TestRequest represents the request body for test.
type TestRequest struct {
	Id *types.ID `json:"id,omitempty"`
	Required *bool `json:"required"`
	String *string `json:"string,omitempty"`
	Default *string `json:"default,omitempty"`
	NullableDefault *string `json:"nullableDefault,omitempty"`
}

// Test calls /test.
func (s *Service) Test(ctx context.Context, req *TestRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/test", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

