// Code generated by tools/gen/main.go. DO NOT EDIT.

package endpoint

import "context"

// Service provides endpoint-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new EndpointService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// EndpointRequest represents the request body for endpoint.
type EndpointRequest struct {
	Endpoint *string `json:"endpoint"`
}

// Endpoint calls /endpoint.
func (s *Service) Endpoint(ctx context.Context, req *EndpointRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/endpoint", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

