// Code generated by tools/gen/main.go. DO NOT EDIT.

package announcements

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides announcements-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new AnnouncementsService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ShowRequest represents the request body for announcements/show.
type ShowRequest struct {
	AnnouncementId *types.ID `json:"announcementId"`
}

// Show calls /announcements/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (types.Announcement, error) {
	var resp types.Announcement
	if err := s.cli.Do(ctx, "/announcements/show", req, &resp); err != nil {
		return *new(types.Announcement), err
	}
	return resp, nil
}

// AnnouncementsRequest represents the request body for announcements.
type AnnouncementsRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Announcements calls /announcements.
func (s *Service) Announcements(ctx context.Context, req *AnnouncementsRequest) ([]types.Announcement, error) {
	var resp []types.Announcement
	if err := s.cli.Do(ctx, "/announcements", req, &resp); err != nil {
		return *new([]types.Announcement), err
	}
	return resp, nil
}

