// Code generated by tools/gen/main.go. DO NOT EDIT.

package blocking

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides blocking-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new BlockingService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// DeleteRequest represents the request body for blocking/delete.
type DeleteRequest struct {
	UserId *types.ID `json:"userId"`
}

// Delete calls /blocking/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/blocking/delete", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ListRequest represents the request body for blocking/list.
type ListRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// List calls /blocking/list (authenticated).
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/blocking/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// CreateRequest represents the request body for blocking/create.
type CreateRequest struct {
	UserId *types.ID `json:"userId"`
}

// Create calls /blocking/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/blocking/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

