// Code generated by tools/gen/main.go. DO NOT EDIT.

package get

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides get-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new GetService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ServerInfo calls /server-info.
func (s *Service) ServerInfo(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/server-info", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// GetAvatarDecorations calls /get-avatar-decorations.
func (s *Service) GetAvatarDecorations(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/get-avatar-decorations", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// PinnedUsers calls /pinned-users.
func (s *Service) PinnedUsers(ctx context.Context) ([]types.UserDetailed, error) {
	var resp []types.UserDetailed
	if err := s.cli.Do(ctx, "/pinned-users", nil, &resp); err != nil {
		return *new([]types.UserDetailed), err
	}
	return resp, nil
}

// Stats calls /stats.
func (s *Service) Stats(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/stats", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// GetOnlineUsersCount calls /get-online-users-count.
func (s *Service) GetOnlineUsersCount(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/get-online-users-count", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

