// Code generated by tools/gen/main.go. DO NOT EDIT.

package roles

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides roles-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new RolesService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ShowRequest represents the request body for roles/show.
type ShowRequest struct {
	RoleId *types.ID `json:"roleId"`
}

// Show calls /roles/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/roles/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// List calls /roles/list (authenticated).
func (s *Service) List(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/roles/list", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// NotesRequest represents the request body for roles/notes.
type NotesRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	RoleId *types.ID `json:"roleId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// Notes calls /roles/notes (authenticated).
func (s *Service) Notes(ctx context.Context, req *NotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/roles/notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// UsersRequest represents the request body for roles/users.
type UsersRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	RoleId *types.ID `json:"roleId"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// Users calls /roles/users.
func (s *Service) Users(ctx context.Context, req *UsersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/roles/users", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

