// Code generated by tools/gen/main.go. DO NOT EDIT.

package emojis

import "context"

// Service provides emojis-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new EmojisService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// Emojis calls /emojis.
func (s *Service) Emojis(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/emojis", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

