// Code generated by tools/gen/main.go. DO NOT EDIT.

package drive

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// FilesUpdateRequest represents the request body for drive/files/update.
type FilesUpdateRequest struct {
	Comment *string `json:"comment,omitempty"`
	FileId *types.ID `json:"fileId"`
	FolderId *types.ID `json:"folderId,omitempty"`
	Name *string `json:"name,omitempty"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
}

// FilesUpdate calls /drive/files/update (authenticated).
func (s *Service) FilesUpdate(ctx context.Context, req *FilesUpdateRequest) (types.DriveFile, error) {
	var resp types.DriveFile
	if err := s.cli.Do(ctx, "/drive/files/update", req, &resp); err != nil {
		return *new(types.DriveFile), err
	}
	return resp, nil
}

// FilesDeleteRequest represents the request body for drive/files/delete.
type FilesDeleteRequest struct {
	FileId *types.ID `json:"fileId"`
}

// FilesDelete calls /drive/files/delete (authenticated).
func (s *Service) FilesDelete(ctx context.Context, req *FilesDeleteRequest) error {
	return s.cli.Do(ctx, "/drive/files/delete", req, nil)
}

// FilesFindRequest represents the request body for drive/files/find.
type FilesFindRequest struct {
	Name *string `json:"name"`
	FolderId *types.ID `json:"folderId,omitempty"`
}

// FilesFind calls /drive/files/find (authenticated).
func (s *Service) FilesFind(ctx context.Context, req *FilesFindRequest) ([]types.DriveFile, error) {
	var resp []types.DriveFile
	if err := s.cli.Do(ctx, "/drive/files/find", req, &resp); err != nil {
		return *new([]types.DriveFile), err
	}
	return resp, nil
}

// FoldersShowRequest represents the request body for drive/folders/show.
type FoldersShowRequest struct {
	FolderId *types.ID `json:"folderId"`
}

// FoldersShow calls /drive/folders/show (authenticated).
func (s *Service) FoldersShow(ctx context.Context, req *FoldersShowRequest) (types.DriveFolder, error) {
	var resp types.DriveFolder
	if err := s.cli.Do(ctx, "/drive/folders/show", req, &resp); err != nil {
		return *new(types.DriveFolder), err
	}
	return resp, nil
}

// FoldersFindRequest represents the request body for drive/folders/find.
type FoldersFindRequest struct {
	Name *string `json:"name"`
	ParentId *types.ID `json:"parentId,omitempty"`
}

// FoldersFind calls /drive/folders/find (authenticated).
func (s *Service) FoldersFind(ctx context.Context, req *FoldersFindRequest) ([]types.DriveFolder, error) {
	var resp []types.DriveFolder
	if err := s.cli.Do(ctx, "/drive/folders/find", req, &resp); err != nil {
		return *new([]types.DriveFolder), err
	}
	return resp, nil
}

// FilesCreate calls /drive/files/create (authenticated).
func (s *Service) FilesCreate(ctx context.Context) (types.DriveFile, error) {
	var resp types.DriveFile
	if err := s.cli.Do(ctx, "/drive/files/create", nil, &resp); err != nil {
		return *new(types.DriveFile), err
	}
	return resp, nil
}

// FilesCheckExistenceRequest represents the request body for drive/files/check-existence.
type FilesCheckExistenceRequest struct {
	Md5 *string `json:"md5"`
}

// FilesCheckExistence calls /drive/files/check-existence (authenticated).
func (s *Service) FilesCheckExistence(ctx context.Context, req *FilesCheckExistenceRequest) (bool, error) {
	var resp bool
	if err := s.cli.Do(ctx, "/drive/files/check-existence", req, &resp); err != nil {
		return *new(bool), err
	}
	return resp, nil
}

// FilesAttachedNotesRequest represents the request body for drive/files/attached-notes.
type FilesAttachedNotesRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	FileId *types.ID `json:"fileId"`
}

// FilesAttachedNotes calls /drive/files/attached-notes (authenticated).
func (s *Service) FilesAttachedNotes(ctx context.Context, req *FilesAttachedNotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/drive/files/attached-notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// FilesAttachedChatMessagesRequest represents the request body for drive/files/attached-chat-messages.
type FilesAttachedChatMessagesRequest struct {
	FileId *types.ID `json:"fileId"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// FilesAttachedChatMessages calls /drive/files/attached-chat-messages (authenticated).
func (s *Service) FilesAttachedChatMessages(ctx context.Context, req *FilesAttachedChatMessagesRequest) ([]types.ChatMessage, error) {
	var resp []types.ChatMessage
	if err := s.cli.Do(ctx, "/drive/files/attached-chat-messages", req, &resp); err != nil {
		return *new([]types.ChatMessage), err
	}
	return resp, nil
}

// FilesUploadFromUrlRequest represents the request body for drive/files/upload-from-url.
type FilesUploadFromUrlRequest struct {
	Url *string `json:"url"`
	FolderId *types.ID `json:"folderId,omitempty"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
	Comment *string `json:"comment,omitempty"`
	Marker *string `json:"marker,omitempty"`
	Force *bool `json:"force,omitempty"`
}

// FilesUploadFromUrl calls /drive/files/upload-from-url (authenticated).
func (s *Service) FilesUploadFromUrl(ctx context.Context, req *FilesUploadFromUrlRequest) error {
	return s.cli.Do(ctx, "/drive/files/upload-from-url", req, nil)
}

// StreamRequest represents the request body for drive/stream.
type StreamRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Type *string `json:"type,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// Stream calls /drive/stream (authenticated).
func (s *Service) Stream(ctx context.Context, req *StreamRequest) ([]types.DriveFile, error) {
	var resp []types.DriveFile
	if err := s.cli.Do(ctx, "/drive/stream", req, &resp); err != nil {
		return *new([]types.DriveFile), err
	}
	return resp, nil
}

// FilesMoveBulkRequest represents the request body for drive/files/move-bulk.
type FilesMoveBulkRequest struct {
	FolderId *types.ID `json:"folderId,omitempty"`
	FileIds []types.ID `json:"fileIds"`
}

// FilesMoveBulk calls /drive/files/move-bulk (authenticated).
func (s *Service) FilesMoveBulk(ctx context.Context, req *FilesMoveBulkRequest) error {
	return s.cli.Do(ctx, "/drive/files/move-bulk", req, nil)
}

// FilesFindByHashRequest represents the request body for drive/files/find-by-hash.
type FilesFindByHashRequest struct {
	Md5 *string `json:"md5"`
}

// FilesFindByHash calls /drive/files/find-by-hash (authenticated).
func (s *Service) FilesFindByHash(ctx context.Context, req *FilesFindByHashRequest) ([]types.DriveFile, error) {
	var resp []types.DriveFile
	if err := s.cli.Do(ctx, "/drive/files/find-by-hash", req, &resp); err != nil {
		return *new([]types.DriveFile), err
	}
	return resp, nil
}

