// Code generated by tools/gen/main.go. DO NOT EDIT.

package meta

import "context"

// Service provides meta-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new MetaService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// MetaRequest represents the request body for meta.
type MetaRequest struct {
	Detail *bool `json:"detail,omitempty"`
}

// Meta calls /meta.
func (s *Service) Meta(ctx context.Context, req *MetaRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/meta", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

