// Code generated by tools/gen/main.go. DO NOT EDIT.

package auth

import "context"

// VerifyEmailRequest represents the request body for verify-email.
type VerifyEmailRequest struct {
	Code *string `json:"code"`
}

// VerifyEmail calls /verify-email.
func (s *Service) VerifyEmail(ctx context.Context, req *VerifyEmailRequest) error {
	return s.cli.Do(ctx, "/verify-email", req, nil)
}

// ResetPasswordRequest represents the request body for reset-password.
type ResetPasswordRequest struct {
	Token *string `json:"token"`
	Password *string `json:"password"`
}

// ResetPassword calls /reset-password.
func (s *Service) ResetPassword(ctx context.Context, req *ResetPasswordRequest) error {
	return s.cli.Do(ctx, "/reset-password", req, nil)
}

// GenTokenRequest represents the request body for miauth/gen-token.
type GenTokenRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IconUrl *string `json:"iconUrl,omitempty"`
	Permission []string `json:"permission"`
	Session *string `json:"session"`
}

// GenToken calls /miauth/gen-token (authenticated).
func (s *Service) GenToken(ctx context.Context, req *GenTokenRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/miauth/gen-token", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RequestResetPasswordRequest represents the request body for request-reset-password.
type RequestResetPasswordRequest struct {
	Username *string `json:"username"`
	Email *string `json:"email"`
}

// RequestResetPassword calls /request-reset-password.
func (s *Service) RequestResetPassword(ctx context.Context, req *RequestResetPasswordRequest) error {
	return s.cli.Do(ctx, "/request-reset-password", req, nil)
}

