// Code generated by tools/gen/main.go. DO NOT EDIT.

package channels

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides channels-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ChannelsService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// MyFavorites calls /channels/my-favorites (authenticated).
func (s *Service) MyFavorites(ctx context.Context) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/my-favorites", nil, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

// ShowRequest represents the request body for channels/show.
type ShowRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// Show calls /channels/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (types.Channel, error) {
	var resp types.Channel
	if err := s.cli.Do(ctx, "/channels/show", req, &resp); err != nil {
		return *new(types.Channel), err
	}
	return resp, nil
}

// MuteCreateRequest represents the request body for channels/mute/create.
type MuteCreateRequest struct {
	ChannelId *types.ID `json:"channelId"`
	ExpiresAt *int64 `json:"expiresAt,omitempty"`
}

// MuteCreate calls /channels/mute/create (authenticated).
func (s *Service) MuteCreate(ctx context.Context, req *MuteCreateRequest) error {
	return s.cli.Do(ctx, "/channels/mute/create", req, nil)
}

// MuteDeleteRequest represents the request body for channels/mute/delete.
type MuteDeleteRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// MuteDelete calls /channels/mute/delete (authenticated).
func (s *Service) MuteDelete(ctx context.Context, req *MuteDeleteRequest) error {
	return s.cli.Do(ctx, "/channels/mute/delete", req, nil)
}

// MuteList calls /channels/mute/list (authenticated).
func (s *Service) MuteList(ctx context.Context) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/mute/list", nil, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

// UpdateRequest represents the request body for channels/update.
type UpdateRequest struct {
	Name *string `json:"name,omitempty"`
	IsArchived *bool `json:"isArchived,omitempty"`
	PinnedNoteIds []types.ID `json:"pinnedNoteIds,omitempty"`
	Color *string `json:"color,omitempty"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
	ChannelId *types.ID `json:"channelId"`
	Description *string `json:"description,omitempty"`
	BannerId *types.ID `json:"bannerId,omitempty"`
	AllowRenoteToExternal *bool `json:"allowRenoteToExternal,omitempty"`
}

// Update calls /channels/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) (types.Channel, error) {
	var resp types.Channel
	if err := s.cli.Do(ctx, "/channels/update", req, &resp); err != nil {
		return *new(types.Channel), err
	}
	return resp, nil
}

// FollowedRequest represents the request body for channels/followed.
type FollowedRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// Followed calls /channels/followed (authenticated).
func (s *Service) Followed(ctx context.Context, req *FollowedRequest) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/followed", req, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

// FavoriteRequest represents the request body for channels/favorite.
type FavoriteRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// Favorite calls /channels/favorite (authenticated).
func (s *Service) Favorite(ctx context.Context, req *FavoriteRequest) error {
	return s.cli.Do(ctx, "/channels/favorite", req, nil)
}

// UnfavoriteRequest represents the request body for channels/unfavorite.
type UnfavoriteRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// Unfavorite calls /channels/unfavorite (authenticated).
func (s *Service) Unfavorite(ctx context.Context, req *UnfavoriteRequest) error {
	return s.cli.Do(ctx, "/channels/unfavorite", req, nil)
}

// FollowRequest represents the request body for channels/follow.
type FollowRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// Follow calls /channels/follow (authenticated).
func (s *Service) Follow(ctx context.Context, req *FollowRequest) error {
	return s.cli.Do(ctx, "/channels/follow", req, nil)
}

// UnfollowRequest represents the request body for channels/unfollow.
type UnfollowRequest struct {
	ChannelId *types.ID `json:"channelId"`
}

// Unfollow calls /channels/unfollow (authenticated).
func (s *Service) Unfollow(ctx context.Context, req *UnfollowRequest) error {
	return s.cli.Do(ctx, "/channels/unfollow", req, nil)
}

// CreateRequest represents the request body for channels/create.
type CreateRequest struct {
	Description *string `json:"description,omitempty"`
	BannerId *types.ID `json:"bannerId,omitempty"`
	Color *string `json:"color,omitempty"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
	AllowRenoteToExternal *bool `json:"allowRenoteToExternal,omitempty"`
	Name *string `json:"name"`
}

// Create calls /channels/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (types.Channel, error) {
	var resp types.Channel
	if err := s.cli.Do(ctx, "/channels/create", req, &resp); err != nil {
		return *new(types.Channel), err
	}
	return resp, nil
}

// SearchRequest represents the request body for channels/search.
type SearchRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Query *string `json:"query"`
	Type *string `json:"type,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// Search calls /channels/search.
func (s *Service) Search(ctx context.Context, req *SearchRequest) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/search", req, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

// OwnedRequest represents the request body for channels/owned.
type OwnedRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Owned calls /channels/owned (authenticated).
func (s *Service) Owned(ctx context.Context, req *OwnedRequest) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/owned", req, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

// Featured calls /channels/featured.
func (s *Service) Featured(ctx context.Context) ([]types.Channel, error) {
	var resp []types.Channel
	if err := s.cli.Do(ctx, "/channels/featured", nil, &resp); err != nil {
		return *new([]types.Channel), err
	}
	return resp, nil
}

