// Code generated by tools/gen/main.go. DO NOT EDIT.

package gallery

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides gallery-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new GalleryService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// PostsShowRequest represents the request body for gallery/posts/show.
type PostsShowRequest struct {
	PostId *types.ID `json:"postId"`
}

// PostsShow calls /gallery/posts/show.
func (s *Service) PostsShow(ctx context.Context, req *PostsShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/gallery/posts/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// PostsDeleteRequest represents the request body for gallery/posts/delete.
type PostsDeleteRequest struct {
	PostId *types.ID `json:"postId"`
}

// PostsDelete calls /gallery/posts/delete (authenticated).
func (s *Service) PostsDelete(ctx context.Context, req *PostsDeleteRequest) error {
	return s.cli.Do(ctx, "/gallery/posts/delete", req, nil)
}

// Popular calls /gallery/popular.
func (s *Service) Popular(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/gallery/popular", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// PostsUpdateRequest represents the request body for gallery/posts/update.
type PostsUpdateRequest struct {
	PostId *types.ID `json:"postId"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	FileIds []types.ID `json:"fileIds,omitempty"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
}

// PostsUpdate calls /gallery/posts/update (authenticated).
func (s *Service) PostsUpdate(ctx context.Context, req *PostsUpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/gallery/posts/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// PostsRequest represents the request body for gallery/posts.
type PostsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// Posts calls /gallery/posts.
func (s *Service) Posts(ctx context.Context, req *PostsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/gallery/posts", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// FeaturedRequest represents the request body for gallery/featured.
type FeaturedRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// Featured calls /gallery/featured.
func (s *Service) Featured(ctx context.Context, req *FeaturedRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/gallery/featured", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// PostsLikeRequest represents the request body for gallery/posts/like.
type PostsLikeRequest struct {
	PostId *types.ID `json:"postId"`
}

// PostsLike calls /gallery/posts/like (authenticated).
func (s *Service) PostsLike(ctx context.Context, req *PostsLikeRequest) error {
	return s.cli.Do(ctx, "/gallery/posts/like", req, nil)
}

// PostsUnlikeRequest represents the request body for gallery/posts/unlike.
type PostsUnlikeRequest struct {
	PostId *types.ID `json:"postId"`
}

// PostsUnlike calls /gallery/posts/unlike (authenticated).
func (s *Service) PostsUnlike(ctx context.Context, req *PostsUnlikeRequest) error {
	return s.cli.Do(ctx, "/gallery/posts/unlike", req, nil)
}

// PostsCreateRequest represents the request body for gallery/posts/create.
type PostsCreateRequest struct {
	Title *string `json:"title"`
	Description *string `json:"description,omitempty"`
	FileIds []types.ID `json:"fileIds"`
	IsSensitive *bool `json:"isSensitive,omitempty"`
}

// PostsCreate calls /gallery/posts/create (authenticated).
func (s *Service) PostsCreate(ctx context.Context, req *PostsCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/gallery/posts/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

