// Code generated by tools/gen/main.go. DO NOT EDIT.

package antennas

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides antennas-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new AntennasService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// UpdateRequest represents the request body for antennas/update.
type UpdateRequest struct {
	Src *string `json:"src,omitempty"`
	UserListId *types.ID `json:"userListId,omitempty"`
	ExcludeKeywords [][]string `json:"excludeKeywords,omitempty"`
	Users []string `json:"users,omitempty"`
	LocalOnly *bool `json:"localOnly,omitempty"`
	WithFile *bool `json:"withFile,omitempty"`
	AntennaId *types.ID `json:"antennaId"`
	Name *string `json:"name,omitempty"`
	Keywords [][]string `json:"keywords,omitempty"`
	CaseSensitive *bool `json:"caseSensitive,omitempty"`
	ExcludeBots *bool `json:"excludeBots,omitempty"`
	WithReplies *bool `json:"withReplies,omitempty"`
	ExcludeNotesInSensitiveChannel *bool `json:"excludeNotesInSensitiveChannel,omitempty"`
}

// Update calls /antennas/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/antennas/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// CreateRequest represents the request body for antennas/create.
type CreateRequest struct {
	ExcludeKeywords [][]string `json:"excludeKeywords"`
	Users []string `json:"users"`
	CaseSensitive *bool `json:"caseSensitive"`
	ExcludeBots *bool `json:"excludeBots,omitempty"`
	WithReplies *bool `json:"withReplies"`
	Name *string `json:"name"`
	UserListId *types.ID `json:"userListId,omitempty"`
	Keywords [][]string `json:"keywords"`
	LocalOnly *bool `json:"localOnly,omitempty"`
	WithFile *bool `json:"withFile"`
	ExcludeNotesInSensitiveChannel *bool `json:"excludeNotesInSensitiveChannel,omitempty"`
	Src *string `json:"src"`
}

// Create calls /antennas/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/antennas/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// List calls /antennas/list (authenticated).
func (s *Service) List(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/antennas/list", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// NotesRequest represents the request body for antennas/notes.
type NotesRequest struct {
	AntennaId *types.ID `json:"antennaId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// Notes calls /antennas/notes (authenticated).
func (s *Service) Notes(ctx context.Context, req *NotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/antennas/notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// DeleteRequest represents the request body for antennas/delete.
type DeleteRequest struct {
	AntennaId *types.ID `json:"antennaId"`
}

// Delete calls /antennas/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/antennas/delete", req, nil)
}

// ShowRequest represents the request body for antennas/show.
type ShowRequest struct {
	AntennaId *types.ID `json:"antennaId"`
}

// Show calls /antennas/show (authenticated).
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/antennas/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

