// Code generated by tools/gen/main.go. DO NOT EDIT.

package clips

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides clips-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ClipsService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// DeleteRequest represents the request body for clips/delete.
type DeleteRequest struct {
	ClipId *types.ID `json:"clipId"`
}

// Delete calls /clips/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/clips/delete", req, nil)
}

// MyFavorites calls /clips/my-favorites (authenticated).
func (s *Service) MyFavorites(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/clips/my-favorites", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ShowRequest represents the request body for clips/show.
type ShowRequest struct {
	ClipId *types.ID `json:"clipId"`
}

// Show calls /clips/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/clips/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ListRequest represents the request body for clips/list.
type ListRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// List calls /clips/list (authenticated).
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/clips/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// UnfavoriteRequest represents the request body for clips/unfavorite.
type UnfavoriteRequest struct {
	ClipId *types.ID `json:"clipId"`
}

// Unfavorite calls /clips/unfavorite (authenticated).
func (s *Service) Unfavorite(ctx context.Context, req *UnfavoriteRequest) error {
	return s.cli.Do(ctx, "/clips/unfavorite", req, nil)
}

// AddNoteRequest represents the request body for clips/add-note.
type AddNoteRequest struct {
	ClipId *types.ID `json:"clipId"`
	NoteId *types.ID `json:"noteId"`
}

// AddNote calls /clips/add-note (authenticated).
func (s *Service) AddNote(ctx context.Context, req *AddNoteRequest) error {
	return s.cli.Do(ctx, "/clips/add-note", req, nil)
}

// UpdateRequest represents the request body for clips/update.
type UpdateRequest struct {
	IsPublic *bool `json:"isPublic,omitempty"`
	Description *string `json:"description,omitempty"`
	ClipId *types.ID `json:"clipId"`
	Name *string `json:"name,omitempty"`
}

// Update calls /clips/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/clips/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// CreateRequest represents the request body for clips/create.
type CreateRequest struct {
	Name *string `json:"name"`
	IsPublic *bool `json:"isPublic,omitempty"`
	Description *string `json:"description,omitempty"`
}

// Create calls /clips/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/clips/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RemoveNoteRequest represents the request body for clips/remove-note.
type RemoveNoteRequest struct {
	ClipId *types.ID `json:"clipId"`
	NoteId *types.ID `json:"noteId"`
}

// RemoveNote calls /clips/remove-note (authenticated).
func (s *Service) RemoveNote(ctx context.Context, req *RemoveNoteRequest) error {
	return s.cli.Do(ctx, "/clips/remove-note", req, nil)
}

// FavoriteRequest represents the request body for clips/favorite.
type FavoriteRequest struct {
	ClipId *types.ID `json:"clipId"`
}

// Favorite calls /clips/favorite (authenticated).
func (s *Service) Favorite(ctx context.Context, req *FavoriteRequest) error {
	return s.cli.Do(ctx, "/clips/favorite", req, nil)
}

// NotesRequest represents the request body for clips/notes.
type NotesRequest struct {
	ClipId *types.ID `json:"clipId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Search *string `json:"search,omitempty"`
}

// Notes calls /clips/notes.
func (s *Service) Notes(ctx context.Context, req *NotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/clips/notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

