// Code generated by tools/gen/main.go. DO NOT EDIT.

package reversi

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides reversi-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ReversiService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// VerifyRequest represents the request body for reversi/verify.
type VerifyRequest struct {
	GameId *types.ID `json:"gameId"`
	Crc32 *string `json:"crc32"`
}

// Verify calls /reversi/verify.
func (s *Service) Verify(ctx context.Context, req *VerifyRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/reversi/verify", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// Invitations calls /reversi/invitations (authenticated).
func (s *Service) Invitations(ctx context.Context) ([]types.UserLite, error) {
	var resp []types.UserLite
	if err := s.cli.Do(ctx, "/reversi/invitations", nil, &resp); err != nil {
		return *new([]types.UserLite), err
	}
	return resp, nil
}

// SurrenderRequest represents the request body for reversi/surrender.
type SurrenderRequest struct {
	GameId *types.ID `json:"gameId"`
}

// Surrender calls /reversi/surrender (authenticated).
func (s *Service) Surrender(ctx context.Context, req *SurrenderRequest) error {
	return s.cli.Do(ctx, "/reversi/surrender", req, nil)
}

// MatchRequest represents the request body for reversi/match.
type MatchRequest struct {
	UserId *types.ID `json:"userId,omitempty"`
	NoIrregularRules *bool `json:"noIrregularRules,omitempty"`
	Multiple *bool `json:"multiple,omitempty"`
}

// Match calls /reversi/match (authenticated).
func (s *Service) Match(ctx context.Context, req *MatchRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/reversi/match", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ShowGameRequest represents the request body for reversi/show-game.
type ShowGameRequest struct {
	GameId *types.ID `json:"gameId"`
}

// ShowGame calls /reversi/show-game.
func (s *Service) ShowGame(ctx context.Context, req *ShowGameRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/reversi/show-game", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// CancelMatchRequest represents the request body for reversi/cancel-match.
type CancelMatchRequest struct {
	UserId *types.ID `json:"userId,omitempty"`
}

// CancelMatch calls /reversi/cancel-match (authenticated).
func (s *Service) CancelMatch(ctx context.Context, req *CancelMatchRequest) error {
	return s.cli.Do(ctx, "/reversi/cancel-match", req, nil)
}

// GamesRequest represents the request body for reversi/games.
type GamesRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	My *bool `json:"my,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// Games calls /reversi/games.
func (s *Service) Games(ctx context.Context, req *GamesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/reversi/games", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

