// Code generated by tools/gen/main.go. DO NOT EDIT.

package federation

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides federation-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new FederationService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// UsersRequest represents the request body for federation/users.
type UsersRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Host *string `json:"host"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// Users calls /federation/users.
func (s *Service) Users(ctx context.Context, req *UsersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/federation/users", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// FollowersRequest represents the request body for federation/followers.
type FollowersRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Host *string `json:"host"`
}

// Followers calls /federation/followers.
func (s *Service) Followers(ctx context.Context, req *FollowersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/federation/followers", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ShowInstanceRequest represents the request body for federation/show-instance.
type ShowInstanceRequest struct {
	Host *string `json:"host"`
}

// ShowInstance calls /federation/show-instance.
func (s *Service) ShowInstance(ctx context.Context, req *ShowInstanceRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/federation/show-instance", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UpdateRemoteUserRequest represents the request body for federation/update-remote-user.
type UpdateRemoteUserRequest struct {
	UserId *types.ID `json:"userId"`
}

// UpdateRemoteUser calls /federation/update-remote-user.
func (s *Service) UpdateRemoteUser(ctx context.Context, req *UpdateRemoteUserRequest) error {
	return s.cli.Do(ctx, "/federation/update-remote-user", req, nil)
}

// InstancesRequest represents the request body for federation/instances.
type InstancesRequest struct {
	Host *string `json:"host,omitempty"`
	Blocked *bool `json:"blocked,omitempty"`
	NotResponding *bool `json:"notResponding,omitempty"`
	Suspended *bool `json:"suspended,omitempty"`
	Silenced *bool `json:"silenced,omitempty"`
	Subscribing *bool `json:"subscribing,omitempty"`
	Publishing *bool `json:"publishing,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Federating *bool `json:"federating,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Sort *string `json:"sort,omitempty"`
}

// Instances calls /federation/instances.
func (s *Service) Instances(ctx context.Context, req *InstancesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/federation/instances", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// StatsRequest represents the request body for federation/stats.
type StatsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
}

// Stats calls /federation/stats.
func (s *Service) Stats(ctx context.Context, req *StatsRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/federation/stats", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// FollowingRequest represents the request body for federation/following.
type FollowingRequest struct {
	Host *string `json:"host"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Following calls /federation/following.
func (s *Service) Following(ctx context.Context, req *FollowingRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/federation/following", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

