// Code generated by tools/gen/main.go. DO NOT EDIT.

package app

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides app-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new AppService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// CreateRequest represents the request body for app/create.
type CreateRequest struct {
	CallbackUrl *string `json:"callbackUrl,omitempty"`
	Name *string `json:"name"`
	Description *string `json:"description"`
	Permission []string `json:"permission"`
}

// Create calls /app/create.
func (s *Service) Create(ctx context.Context, req *CreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/app/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ShowRequest represents the request body for app/show.
type ShowRequest struct {
	AppId *types.ID `json:"appId"`
}

// Show calls /app/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/app/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

