// Code generated by tools/gen/main.go. DO NOT EDIT.

package charts

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides charts-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ChartsService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// NotesRequest represents the request body for charts/notes.
type NotesRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Notes calls /charts/notes.
func (s *Service) Notes(ctx context.Context, req *NotesRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/notes", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UserNotesRequest represents the request body for charts/user/notes.
type UserNotesRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	UserId *types.ID `json:"userId"`
}

// UserNotes calls /charts/user/notes.
func (s *Service) UserNotes(ctx context.Context, req *UserNotesRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/user/notes", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// DriveRequest represents the request body for charts/drive.
type DriveRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Drive calls /charts/drive.
func (s *Service) Drive(ctx context.Context, req *DriveRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/drive", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ApRequestRequest represents the request body for charts/ap-request.
type ApRequestRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// ApRequest calls /charts/ap-request.
func (s *Service) ApRequest(ctx context.Context, req *ApRequestRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/ap-request", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UserFollowingRequest represents the request body for charts/user/following.
type UserFollowingRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	UserId *types.ID `json:"userId"`
}

// UserFollowing calls /charts/user/following.
func (s *Service) UserFollowing(ctx context.Context, req *UserFollowingRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/user/following", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UserPvRequest represents the request body for charts/user/pv.
type UserPvRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	UserId *types.ID `json:"userId"`
}

// UserPv calls /charts/user/pv.
func (s *Service) UserPv(ctx context.Context, req *UserPvRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/user/pv", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UsersRequest represents the request body for charts/users.
type UsersRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Users calls /charts/users.
func (s *Service) Users(ctx context.Context, req *UsersRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/users", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ActiveUsersRequest represents the request body for charts/active-users.
type ActiveUsersRequest struct {
	Offset *int64 `json:"offset,omitempty"`
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
}

// ActiveUsers calls /charts/active-users.
func (s *Service) ActiveUsers(ctx context.Context, req *ActiveUsersRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/active-users", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// InstanceRequest represents the request body for charts/instance.
type InstanceRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Host *string `json:"host"`
}

// Instance calls /charts/instance.
func (s *Service) Instance(ctx context.Context, req *InstanceRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/instance", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// FederationRequest represents the request body for charts/federation.
type FederationRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Span *string `json:"span"`
}

// Federation calls /charts/federation.
func (s *Service) Federation(ctx context.Context, req *FederationRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/federation", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UserDriveRequest represents the request body for charts/user/drive.
type UserDriveRequest struct {
	Span *string `json:"span"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	UserId *types.ID `json:"userId"`
}

// UserDrive calls /charts/user/drive.
func (s *Service) UserDrive(ctx context.Context, req *UserDriveRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/user/drive", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UserReactionsRequest represents the request body for charts/user/reactions.
type UserReactionsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	UserId *types.ID `json:"userId"`
	Span *string `json:"span"`
}

// UserReactions calls /charts/user/reactions.
func (s *Service) UserReactions(ctx context.Context, req *UserReactionsRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/charts/user/reactions", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

