// Code generated by tools/gen/main.go. DO NOT EDIT.

package account

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides account (/i/)-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new AccountService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// IExportAntennas calls /i/export-antennas (authenticated).
func (s *Service) IExportAntennas(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-antennas", nil, nil)
}

// IExportBlocking calls /i/export-blocking (authenticated).
func (s *Service) IExportBlocking(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-blocking", nil, nil)
}

// IPinRequest represents the request body for i/pin.
type IPinRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// IPin calls /i/pin (authenticated).
func (s *Service) IPin(ctx context.Context, req *IPinRequest) (types.MeDetailed, error) {
	var resp types.MeDetailed
	if err := s.cli.Do(ctx, "/i/pin", req, &resp); err != nil {
		return *new(types.MeDetailed), err
	}
	return resp, nil
}

// IRegistryGetRequest represents the request body for i/registry/get.
type IRegistryGetRequest struct {
	Domain *string `json:"domain,omitempty"`
	Key *string `json:"key"`
	Scope []string `json:"scope"`
}

// IRegistryGet calls /i/registry/get (authenticated).
func (s *Service) IRegistryGet(ctx context.Context, req *IRegistryGetRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/registry/get", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IReadAnnouncementRequest represents the request body for i/read-announcement.
type IReadAnnouncementRequest struct {
	AnnouncementId *types.ID `json:"announcementId"`
}

// IReadAnnouncement calls /i/read-announcement (authenticated).
func (s *Service) IReadAnnouncement(ctx context.Context, req *IReadAnnouncementRequest) error {
	return s.cli.Do(ctx, "/i/read-announcement", req, nil)
}

// IWebhooksUpdateRequest represents the request body for i/webhooks/update.
type IWebhooksUpdateRequest struct {
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Secret *string `json:"secret,omitempty"`
	On []string `json:"on,omitempty"`
	Active *bool `json:"active,omitempty"`
	WebhookId *types.ID `json:"webhookId"`
}

// IWebhooksUpdate calls /i/webhooks/update (authenticated).
func (s *Service) IWebhooksUpdate(ctx context.Context, req *IWebhooksUpdateRequest) error {
	return s.cli.Do(ctx, "/i/webhooks/update", req, nil)
}

// IClaimAchievementRequest represents the request body for i/claim-achievement.
type IClaimAchievementRequest struct {
	Name *string `json:"name"`
}

// IClaimAchievement calls /i/claim-achievement (authenticated).
func (s *Service) IClaimAchievement(ctx context.Context, req *IClaimAchievementRequest) error {
	return s.cli.Do(ctx, "/i/claim-achievement", req, nil)
}

// IImportAntennasRequest represents the request body for i/import-antennas.
type IImportAntennasRequest struct {
	FileId *types.ID `json:"fileId"`
}

// IImportAntennas calls /i/import-antennas (authenticated).
func (s *Service) IImportAntennas(ctx context.Context, req *IImportAntennasRequest) error {
	return s.cli.Do(ctx, "/i/import-antennas", req, nil)
}

// I2faUpdateKeyRequest represents the request body for i/2fa/update-key.
type I2faUpdateKeyRequest struct {
	Name *string `json:"name"`
	CredentialId *string `json:"credentialId"`
}

// I2faUpdateKey calls /i/2fa/update-key (authenticated).
func (s *Service) I2faUpdateKey(ctx context.Context, req *I2faUpdateKeyRequest) error {
	return s.cli.Do(ctx, "/i/2fa/update-key", req, nil)
}

// IRevokeTokenRequest represents the request body for i/revoke-token.
type IRevokeTokenRequest struct {
	TokenId *types.ID `json:"tokenId"`
	Token *string `json:"token"`
}

// IRevokeToken calls /i/revoke-token (authenticated).
func (s *Service) IRevokeToken(ctx context.Context, req *IRevokeTokenRequest) error {
	return s.cli.Do(ctx, "/i/revoke-token", req, nil)
}

// I2faKeyDoneRequest represents the request body for i/2fa/key-done.
type I2faKeyDoneRequest struct {
	Password *string `json:"password"`
	Token *string `json:"token,omitempty"`
	Name *string `json:"name"`
	Credential any `json:"credential"`
}

// I2faKeyDone calls /i/2fa/key-done (authenticated).
func (s *Service) I2faKeyDone(ctx context.Context, req *I2faKeyDoneRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/2fa/key-done", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// I2faRemoveKeyRequest represents the request body for i/2fa/remove-key.
type I2faRemoveKeyRequest struct {
	Token *string `json:"token,omitempty"`
	CredentialId *string `json:"credentialId"`
	Password *string `json:"password"`
}

// I2faRemoveKey calls /i/2fa/remove-key (authenticated).
func (s *Service) I2faRemoveKey(ctx context.Context, req *I2faRemoveKeyRequest) error {
	return s.cli.Do(ctx, "/i/2fa/remove-key", req, nil)
}

// IImportUserListsRequest represents the request body for i/import-user-lists.
type IImportUserListsRequest struct {
	FileId *types.ID `json:"fileId"`
}

// IImportUserLists calls /i/import-user-lists (authenticated).
func (s *Service) IImportUserLists(ctx context.Context, req *IImportUserListsRequest) error {
	return s.cli.Do(ctx, "/i/import-user-lists", req, nil)
}

// I2faPasswordLessRequest represents the request body for i/2fa/password-less.
type I2faPasswordLessRequest struct {
	Value *bool `json:"value"`
}

// I2faPasswordLess calls /i/2fa/password-less (authenticated).
func (s *Service) I2faPasswordLess(ctx context.Context, req *I2faPasswordLessRequest) error {
	return s.cli.Do(ctx, "/i/2fa/password-less", req, nil)
}

// IWebhooksTestRequest represents the request body for i/webhooks/test.
type IWebhooksTestRequest struct {
	Override any `json:"override,omitempty"`
	WebhookId *types.ID `json:"webhookId"`
	Type *string `json:"type"`
}

// IWebhooksTest calls /i/webhooks/test (authenticated).
func (s *Service) IWebhooksTest(ctx context.Context, req *IWebhooksTestRequest) error {
	return s.cli.Do(ctx, "/i/webhooks/test", req, nil)
}

// IImportMutingRequest represents the request body for i/import-muting.
type IImportMutingRequest struct {
	FileId *types.ID `json:"fileId"`
}

// IImportMuting calls /i/import-muting (authenticated).
func (s *Service) IImportMuting(ctx context.Context, req *IImportMutingRequest) error {
	return s.cli.Do(ctx, "/i/import-muting", req, nil)
}

// IExportMute calls /i/export-mute (authenticated).
func (s *Service) IExportMute(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-mute", nil, nil)
}

// IPagesRequest represents the request body for i/pages.
type IPagesRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// IPages calls /i/pages (authenticated).
func (s *Service) IPages(ctx context.Context, req *IPagesRequest) ([]types.Page, error) {
	var resp []types.Page
	if err := s.cli.Do(ctx, "/i/pages", req, &resp); err != nil {
		return *new([]types.Page), err
	}
	return resp, nil
}

// IRegistryGetAllRequest represents the request body for i/registry/get-all.
type IRegistryGetAllRequest struct {
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
}

// IRegistryGetAll calls /i/registry/get-all (authenticated).
func (s *Service) IRegistryGetAll(ctx context.Context, req *IRegistryGetAllRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/registry/get-all", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IMoveRequest represents the request body for i/move.
type IMoveRequest struct {
	MoveToAccount *string `json:"moveToAccount"`
}

// IMove calls /i/move (authenticated).
func (s *Service) IMove(ctx context.Context, req *IMoveRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/move", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IRegistrySetRequest represents the request body for i/registry/set.
type IRegistrySetRequest struct {
	Key *string `json:"key"`
	Value any `json:"value"`
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
}

// IRegistrySet calls /i/registry/set (authenticated).
func (s *Service) IRegistrySet(ctx context.Context, req *IRegistrySetRequest) error {
	return s.cli.Do(ctx, "/i/registry/set", req, nil)
}

// IDeleteAccountRequest represents the request body for i/delete-account.
type IDeleteAccountRequest struct {
	Password *string `json:"password"`
	Token *string `json:"token,omitempty"`
}

// IDeleteAccount calls /i/delete-account (authenticated).
func (s *Service) IDeleteAccount(ctx context.Context, req *IDeleteAccountRequest) error {
	return s.cli.Do(ctx, "/i/delete-account", req, nil)
}

// IImportFollowingRequest represents the request body for i/import-following.
type IImportFollowingRequest struct {
	FileId *types.ID `json:"fileId"`
	WithReplies *bool `json:"withReplies,omitempty"`
}

// IImportFollowing calls /i/import-following (authenticated).
func (s *Service) IImportFollowing(ctx context.Context, req *IImportFollowingRequest) error {
	return s.cli.Do(ctx, "/i/import-following", req, nil)
}

// IRegistryRemoveRequest represents the request body for i/registry/remove.
type IRegistryRemoveRequest struct {
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
	Key *string `json:"key"`
}

// IRegistryRemove calls /i/registry/remove (authenticated).
func (s *Service) IRegistryRemove(ctx context.Context, req *IRegistryRemoveRequest) error {
	return s.cli.Do(ctx, "/i/registry/remove", req, nil)
}

// IExportFollowingRequest represents the request body for i/export-following.
type IExportFollowingRequest struct {
	ExcludeInactive *bool `json:"excludeInactive,omitempty"`
	ExcludeMuting *bool `json:"excludeMuting,omitempty"`
}

// IExportFollowing calls /i/export-following (authenticated).
func (s *Service) IExportFollowing(ctx context.Context, req *IExportFollowingRequest) error {
	return s.cli.Do(ctx, "/i/export-following", req, nil)
}

// IAuthorizedAppsRequest represents the request body for i/authorized-apps.
type IAuthorizedAppsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Sort *string `json:"sort,omitempty"`
}

// IAuthorizedApps calls /i/authorized-apps (authenticated).
func (s *Service) IAuthorizedApps(ctx context.Context, req *IAuthorizedAppsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/authorized-apps", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IExportUserLists calls /i/export-user-lists (authenticated).
func (s *Service) IExportUserLists(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-user-lists", nil, nil)
}

// IPageLikesRequest represents the request body for i/page-likes.
type IPageLikesRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// IPageLikes calls /i/page-likes (authenticated).
func (s *Service) IPageLikes(ctx context.Context, req *IPageLikesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/page-likes", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IWebhooksDeleteRequest represents the request body for i/webhooks/delete.
type IWebhooksDeleteRequest struct {
	WebhookId *types.ID `json:"webhookId"`
}

// IWebhooksDelete calls /i/webhooks/delete (authenticated).
func (s *Service) IWebhooksDelete(ctx context.Context, req *IWebhooksDeleteRequest) error {
	return s.cli.Do(ctx, "/i/webhooks/delete", req, nil)
}

// IImportBlockingRequest represents the request body for i/import-blocking.
type IImportBlockingRequest struct {
	FileId *types.ID `json:"fileId"`
}

// IImportBlocking calls /i/import-blocking (authenticated).
func (s *Service) IImportBlocking(ctx context.Context, req *IImportBlockingRequest) error {
	return s.cli.Do(ctx, "/i/import-blocking", req, nil)
}

// I2faDoneRequest represents the request body for i/2fa/done.
type I2faDoneRequest struct {
	Token *string `json:"token"`
}

// I2faDone calls /i/2fa/done (authenticated).
func (s *Service) I2faDone(ctx context.Context, req *I2faDoneRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/2fa/done", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IExportFavorites calls /i/export-favorites (authenticated).
func (s *Service) IExportFavorites(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-favorites", nil, nil)
}

// IGalleryLikesRequest represents the request body for i/gallery/likes.
type IGalleryLikesRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// IGalleryLikes calls /i/gallery/likes (authenticated).
func (s *Service) IGalleryLikes(ctx context.Context, req *IGalleryLikesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/gallery/likes", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IRegistryKeysWithTypeRequest represents the request body for i/registry/keys-with-type.
type IRegistryKeysWithTypeRequest struct {
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
}

// IRegistryKeysWithType calls /i/registry/keys-with-type (authenticated).
func (s *Service) IRegistryKeysWithType(ctx context.Context, req *IRegistryKeysWithTypeRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/registry/keys-with-type", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IGalleryPostsRequest represents the request body for i/gallery/posts.
type IGalleryPostsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// IGalleryPosts calls /i/gallery/posts (authenticated).
func (s *Service) IGalleryPosts(ctx context.Context, req *IGalleryPostsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/gallery/posts", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IWebhooksList calls /i/webhooks/list (authenticated).
func (s *Service) IWebhooksList(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/webhooks/list", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IChangePasswordRequest represents the request body for i/change-password.
type IChangePasswordRequest struct {
	CurrentPassword *string `json:"currentPassword"`
	NewPassword *string `json:"newPassword"`
	Token *string `json:"token,omitempty"`
}

// IChangePassword calls /i/change-password (authenticated).
func (s *Service) IChangePassword(ctx context.Context, req *IChangePasswordRequest) error {
	return s.cli.Do(ctx, "/i/change-password", req, nil)
}

// IUnpinRequest represents the request body for i/unpin.
type IUnpinRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// IUnpin calls /i/unpin (authenticated).
func (s *Service) IUnpin(ctx context.Context, req *IUnpinRequest) (types.MeDetailed, error) {
	var resp types.MeDetailed
	if err := s.cli.Do(ctx, "/i/unpin", req, &resp); err != nil {
		return *new(types.MeDetailed), err
	}
	return resp, nil
}

// IUpdateRequest represents the request body for i/update.
type IUpdateRequest struct {
	Lang *string `json:"lang,omitempty"`
	FollowersVisibility *string `json:"followersVisibility,omitempty"`
	MutedWords []any `json:"mutedWords,omitempty"`
	AutoSensitive *bool `json:"autoSensitive,omitempty"`
	AvatarDecorations []any `json:"avatarDecorations,omitempty"`
	AutoAcceptFollowed *bool `json:"autoAcceptFollowed,omitempty"`
	MakeNotesHiddenBefore *int64 `json:"makeNotesHiddenBefore,omitempty"`
	MutedInstances []string `json:"mutedInstances,omitempty"`
	BannerId *types.ID `json:"bannerId,omitempty"`
	Fields []any `json:"fields,omitempty"`
	RequireSigninToViewContents *bool `json:"requireSigninToViewContents,omitempty"`
	ReceiveAnnouncementEmail *bool `json:"receiveAnnouncementEmail,omitempty"`
	PinnedPageId *types.ID `json:"pinnedPageId,omitempty"`
	AvatarId *types.ID `json:"avatarId,omitempty"`
	CarefulBot *bool `json:"carefulBot,omitempty"`
	PreventAiLearning *bool `json:"preventAiLearning,omitempty"`
	FollowingVisibility *string `json:"followingVisibility,omitempty"`
	ChatScope *string `json:"chatScope,omitempty"`
	NotificationRecieveConfig any `json:"notificationRecieveConfig,omitempty"`
	EmailNotificationTypes []string `json:"emailNotificationTypes,omitempty"`
	Location *string `json:"location,omitempty"`
	IsExplorable *bool `json:"isExplorable,omitempty"`
	HideOnlineStatus *bool `json:"hideOnlineStatus,omitempty"`
	NoCrawle *bool `json:"noCrawle,omitempty"`
	AlwaysMarkNsfw *bool `json:"alwaysMarkNsfw,omitempty"`
	HardMutedWords []any `json:"hardMutedWords,omitempty"`
	Description *string `json:"description,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
	IsLocked *bool `json:"isLocked,omitempty"`
	MakeNotesFollowersOnlyBefore *int64 `json:"makeNotesFollowersOnlyBefore,omitempty"`
	IsCat *bool `json:"isCat,omitempty"`
	InjectFeaturedNote *bool `json:"injectFeaturedNote,omitempty"`
	FollowedMessage *string `json:"followedMessage,omitempty"`
	PublicReactions *bool `json:"publicReactions,omitempty"`
	IsBot *bool `json:"isBot,omitempty"`
	AlsoKnownAs []string `json:"alsoKnownAs,omitempty"`
	Name *string `json:"name,omitempty"`
}

// IUpdate calls /i/update (authenticated).
func (s *Service) IUpdate(ctx context.Context, req *IUpdateRequest) (types.MeDetailed, error) {
	var resp types.MeDetailed
	if err := s.cli.Do(ctx, "/i/update", req, &resp); err != nil {
		return *new(types.MeDetailed), err
	}
	return resp, nil
}

// IUpdateEmailRequest represents the request body for i/update-email.
type IUpdateEmailRequest struct {
	Password *string `json:"password"`
	Email *string `json:"email,omitempty"`
	Token *string `json:"token,omitempty"`
}

// IUpdateEmail calls /i/update-email (authenticated).
func (s *Service) IUpdateEmail(ctx context.Context, req *IUpdateEmailRequest) (types.MeDetailed, error) {
	var resp types.MeDetailed
	if err := s.cli.Do(ctx, "/i/update-email", req, &resp); err != nil {
		return *new(types.MeDetailed), err
	}
	return resp, nil
}

// AppsRequest represents the request body for my/apps.
type AppsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Apps calls /my/apps (authenticated).
func (s *Service) Apps(ctx context.Context, req *AppsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/my/apps", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ISigninHistoryRequest represents the request body for i/signin-history.
type ISigninHistoryRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// ISigninHistory calls /i/signin-history (authenticated).
func (s *Service) ISigninHistory(ctx context.Context, req *ISigninHistoryRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/signin-history", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IWebhooksShowRequest represents the request body for i/webhooks/show.
type IWebhooksShowRequest struct {
	WebhookId *types.ID `json:"webhookId"`
}

// IWebhooksShow calls /i/webhooks/show (authenticated).
func (s *Service) IWebhooksShow(ctx context.Context, req *IWebhooksShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/webhooks/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IRegistryGetDetailRequest represents the request body for i/registry/get-detail.
type IRegistryGetDetailRequest struct {
	Key *string `json:"key"`
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
}

// IRegistryGetDetail calls /i/registry/get-detail (authenticated).
func (s *Service) IRegistryGetDetail(ctx context.Context, req *IRegistryGetDetailRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/registry/get-detail", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IExportNotes calls /i/export-notes (authenticated).
func (s *Service) IExportNotes(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-notes", nil, nil)
}

// IWebhooksCreateRequest represents the request body for i/webhooks/create.
type IWebhooksCreateRequest struct {
	Secret *string `json:"secret,omitempty"`
	On []string `json:"on"`
	Name *string `json:"name"`
	Url *string `json:"url"`
}

// IWebhooksCreate calls /i/webhooks/create (authenticated).
func (s *Service) IWebhooksCreate(ctx context.Context, req *IWebhooksCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/webhooks/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// I2faRegisterRequest represents the request body for i/2fa/register.
type I2faRegisterRequest struct {
	Token *string `json:"token,omitempty"`
	Password *string `json:"password"`
}

// I2faRegister calls /i/2fa/register (authenticated).
func (s *Service) I2faRegister(ctx context.Context, req *I2faRegisterRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/2fa/register", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// I2faUnregisterRequest represents the request body for i/2fa/unregister.
type I2faUnregisterRequest struct {
	Password *string `json:"password"`
	Token *string `json:"token,omitempty"`
}

// I2faUnregister calls /i/2fa/unregister (authenticated).
func (s *Service) I2faUnregister(ctx context.Context, req *I2faUnregisterRequest) error {
	return s.cli.Do(ctx, "/i/2fa/unregister", req, nil)
}

// IFavoritesRequest represents the request body for i/favorites.
type IFavoritesRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// IFavorites calls /i/favorites (authenticated).
func (s *Service) IFavorites(ctx context.Context, req *IFavoritesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/favorites", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// I2faRegisterKeyRequest represents the request body for i/2fa/register-key.
type I2faRegisterKeyRequest struct {
	Password *string `json:"password"`
	Token *string `json:"token,omitempty"`
}

// I2faRegisterKey calls /i/2fa/register-key (authenticated).
func (s *Service) I2faRegisterKey(ctx context.Context, req *I2faRegisterKeyRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/i/2fa/register-key", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// IExportClips calls /i/export-clips (authenticated).
func (s *Service) IExportClips(ctx context.Context) error {
	return s.cli.Do(ctx, "/i/export-clips", nil, nil)
}

// IRegenerateTokenRequest represents the request body for i/regenerate-token.
type IRegenerateTokenRequest struct {
	Password *string `json:"password"`
}

// IRegenerateToken calls /i/regenerate-token (authenticated).
func (s *Service) IRegenerateToken(ctx context.Context, req *IRegenerateTokenRequest) error {
	return s.cli.Do(ctx, "/i/regenerate-token", req, nil)
}

// IRegistryScopesWithDomain calls /i/registry/scopes-with-domain (authenticated).
func (s *Service) IRegistryScopesWithDomain(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/registry/scopes-with-domain", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// IRegistryKeysRequest represents the request body for i/registry/keys.
type IRegistryKeysRequest struct {
	Scope []string `json:"scope"`
	Domain *string `json:"domain,omitempty"`
}

// IRegistryKeys calls /i/registry/keys (authenticated).
func (s *Service) IRegistryKeys(ctx context.Context, req *IRegistryKeysRequest) ([]string, error) {
	var resp []string
	if err := s.cli.Do(ctx, "/i/registry/keys", req, &resp); err != nil {
		return *new([]string), err
	}
	return resp, nil
}

// IAppsRequest represents the request body for i/apps.
type IAppsRequest struct {
	Sort *string `json:"sort,omitempty"`
}

// IApps calls /i/apps (authenticated).
func (s *Service) IApps(ctx context.Context, req *IAppsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/i/apps", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

