// Code generated by tools/gen/main.go. DO NOT EDIT.

package admin

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// UpdateAbuseUserReportRequest represents the request body for admin/update-abuse-user-report.
type UpdateAbuseUserReportRequest struct {
	ReportId *types.ID `json:"reportId"`
	ModerationNote *string `json:"moderationNote,omitempty"`
}

// UpdateAbuseUserReport calls /admin/update-abuse-user-report (authenticated).
func (s *Service) UpdateAbuseUserReport(ctx context.Context, req *UpdateAbuseUserReportRequest) error {
	return s.cli.Do(ctx, "/admin/update-abuse-user-report", req, nil)
}

// ResetDb calls /reset-db.
func (s *Service) ResetDb(ctx context.Context) error {
	return s.cli.Do(ctx, "/reset-db", nil, nil)
}

// FederationRefreshRemoteInstanceMetadataRequest represents the request body for admin/federation/refresh-remote-instance-metadata.
type FederationRefreshRemoteInstanceMetadataRequest struct {
	Host *string `json:"host"`
}

// FederationRefreshRemoteInstanceMetadata calls /admin/federation/refresh-remote-instance-metadata (authenticated).
func (s *Service) FederationRefreshRemoteInstanceMetadata(ctx context.Context, req *FederationRefreshRemoteInstanceMetadataRequest) error {
	return s.cli.Do(ctx, "/admin/federation/refresh-remote-instance-metadata", req, nil)
}

// GetTableStats calls /admin/get-table-stats (authenticated).
func (s *Service) GetTableStats(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/get-table-stats", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// QueueJobsRequest represents the request body for admin/queue/jobs.
type QueueJobsRequest struct {
	Queue *string `json:"queue"`
	State []string `json:"state"`
	Search *string `json:"search,omitempty"`
}

// QueueJobs calls /admin/queue/jobs (authenticated).
func (s *Service) QueueJobs(ctx context.Context, req *QueueJobsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/queue/jobs", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// GetUserIpsRequest represents the request body for admin/get-user-ips.
type GetUserIpsRequest struct {
	UserId *types.ID `json:"userId"`
}

// GetUserIps calls /admin/get-user-ips (authenticated).
func (s *Service) GetUserIps(ctx context.Context, req *GetUserIpsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/get-user-ips", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// QueueStats calls /admin/queue/stats (authenticated).
func (s *Service) QueueStats(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/queue/stats", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RelaysAddRequest represents the request body for admin/relays/add.
type RelaysAddRequest struct {
	Inbox *string `json:"inbox"`
}

// RelaysAdd calls /admin/relays/add (authenticated).
func (s *Service) RelaysAdd(ctx context.Context, req *RelaysAddRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/relays/add", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RelaysRemoveRequest represents the request body for admin/relays/remove.
type RelaysRemoveRequest struct {
	Inbox *string `json:"inbox"`
}

// RelaysRemove calls /admin/relays/remove (authenticated).
func (s *Service) RelaysRemove(ctx context.Context, req *RelaysRemoveRequest) error {
	return s.cli.Do(ctx, "/admin/relays/remove", req, nil)
}

// FederationDeleteAllFilesRequest represents the request body for admin/federation/delete-all-files.
type FederationDeleteAllFilesRequest struct {
	Host *string `json:"host"`
}

// FederationDeleteAllFiles calls /admin/federation/delete-all-files (authenticated).
func (s *Service) FederationDeleteAllFiles(ctx context.Context, req *FederationDeleteAllFilesRequest) error {
	return s.cli.Do(ctx, "/admin/federation/delete-all-files", req, nil)
}

// PromoCreateRequest represents the request body for admin/promo/create.
type PromoCreateRequest struct {
	NoteId *types.ID `json:"noteId"`
	ExpiresAt *int64 `json:"expiresAt"`
}

// PromoCreate calls /admin/promo/create (authenticated).
func (s *Service) PromoCreate(ctx context.Context, req *PromoCreateRequest) error {
	return s.cli.Do(ctx, "/admin/promo/create", req, nil)
}

// QueueDeliverDelayed calls /admin/queue/deliver-delayed (authenticated).
func (s *Service) QueueDeliverDelayed(ctx context.Context) ([][]any, error) {
	var resp [][]any
	if err := s.cli.Do(ctx, "/admin/queue/deliver-delayed", nil, &resp); err != nil {
		return *new([][]any), err
	}
	return resp, nil
}

// QueueRemoveJobRequest represents the request body for admin/queue/remove-job.
type QueueRemoveJobRequest struct {
	Queue *string `json:"queue"`
	JobId *string `json:"jobId"`
}

// QueueRemoveJob calls /admin/queue/remove-job (authenticated).
func (s *Service) QueueRemoveJob(ctx context.Context, req *QueueRemoveJobRequest) error {
	return s.cli.Do(ctx, "/admin/queue/remove-job", req, nil)
}

// RolesShowRequest represents the request body for admin/roles/show.
type RolesShowRequest struct {
	RoleId *types.ID `json:"roleId"`
}

// RolesShow calls /admin/roles/show (authenticated).
func (s *Service) RolesShow(ctx context.Context, req *RolesShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/roles/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RolesUpdateDefaultPoliciesRequest represents the request body for admin/roles/update-default-policies.
type RolesUpdateDefaultPoliciesRequest struct {
	Policies any `json:"policies"`
}

// RolesUpdateDefaultPolicies calls /admin/roles/update-default-policies (authenticated).
func (s *Service) RolesUpdateDefaultPolicies(ctx context.Context, req *RolesUpdateDefaultPoliciesRequest) error {
	return s.cli.Do(ctx, "/admin/roles/update-default-policies", req, nil)
}

// RolesUsersRequest represents the request body for admin/roles/users.
type RolesUsersRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	RoleId *types.ID `json:"roleId"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// RolesUsers calls /admin/roles/users.
func (s *Service) RolesUsers(ctx context.Context, req *RolesUsersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/roles/users", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// SystemWebhookUpdateRequest represents the request body for admin/system-webhook/update.
type SystemWebhookUpdateRequest struct {
	Id *types.ID `json:"id"`
	IsActive *bool `json:"isActive"`
	Name *string `json:"name"`
	On []string `json:"on"`
	Url *string `json:"url"`
	Secret *string `json:"secret,omitempty"`
}

// SystemWebhookUpdate calls /admin/system-webhook/update (authenticated).
func (s *Service) SystemWebhookUpdate(ctx context.Context, req *SystemWebhookUpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/system-webhook/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// EmojiImportZipRequest represents the request body for admin/emoji/import-zip.
type EmojiImportZipRequest struct {
	FileId *types.ID `json:"fileId"`
}

// EmojiImportZip calls /admin/emoji/import-zip (authenticated).
func (s *Service) EmojiImportZip(ctx context.Context, req *EmojiImportZipRequest) error {
	return s.cli.Do(ctx, "/admin/emoji/import-zip", req, nil)
}

// EmojiSetLicenseBulkRequest represents the request body for admin/emoji/set-license-bulk.
type EmojiSetLicenseBulkRequest struct {
	Ids []types.ID `json:"ids"`
	License *string `json:"license,omitempty"`
}

// EmojiSetLicenseBulk calls /admin/emoji/set-license-bulk (authenticated).
func (s *Service) EmojiSetLicenseBulk(ctx context.Context, req *EmojiSetLicenseBulkRequest) error {
	return s.cli.Do(ctx, "/admin/emoji/set-license-bulk", req, nil)
}

// SendEmailRequest represents the request body for admin/send-email.
type SendEmailRequest struct {
	To *string `json:"to"`
	Subject *string `json:"subject"`
	Text *string `json:"text"`
}

// SendEmail calls /admin/send-email (authenticated).
func (s *Service) SendEmail(ctx context.Context, req *SendEmailRequest) error {
	return s.cli.Do(ctx, "/admin/send-email", req, nil)
}

// EmojiAddAliasesBulkRequest represents the request body for admin/emoji/add-aliases-bulk.
type EmojiAddAliasesBulkRequest struct {
	Ids []types.ID `json:"ids"`
	Aliases []string `json:"aliases"`
}

// EmojiAddAliasesBulk calls /admin/emoji/add-aliases-bulk (authenticated).
func (s *Service) EmojiAddAliasesBulk(ctx context.Context, req *EmojiAddAliasesBulkRequest) error {
	return s.cli.Do(ctx, "/admin/emoji/add-aliases-bulk", req, nil)
}

// CaptchaCurrent calls /admin/captcha/current (authenticated).
func (s *Service) CaptchaCurrent(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/captcha/current", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// SystemWebhookDeleteRequest represents the request body for admin/system-webhook/delete.
type SystemWebhookDeleteRequest struct {
	Id *types.ID `json:"id"`
}

// SystemWebhookDelete calls /admin/system-webhook/delete (authenticated).
func (s *Service) SystemWebhookDelete(ctx context.Context, req *SystemWebhookDeleteRequest) error {
	return s.cli.Do(ctx, "/admin/system-webhook/delete", req, nil)
}

// UnsetUserAvatarRequest represents the request body for admin/unset-user-avatar.
type UnsetUserAvatarRequest struct {
	UserId *types.ID `json:"userId"`
}

// UnsetUserAvatar calls /admin/unset-user-avatar (authenticated).
func (s *Service) UnsetUserAvatar(ctx context.Context, req *UnsetUserAvatarRequest) error {
	return s.cli.Do(ctx, "/admin/unset-user-avatar", req, nil)
}

// CaptchaSaveRequest represents the request body for admin/captcha/save.
type CaptchaSaveRequest struct {
	Provider *string `json:"provider"`
	CaptchaResult *string `json:"captchaResult,omitempty"`
	Sitekey *string `json:"sitekey,omitempty"`
	Secret *string `json:"secret,omitempty"`
	InstanceUrl *string `json:"instanceUrl,omitempty"`
}

// CaptchaSave calls /admin/captcha/save (authenticated).
func (s *Service) CaptchaSave(ctx context.Context, req *CaptchaSaveRequest) error {
	return s.cli.Do(ctx, "/admin/captcha/save", req, nil)
}

// FederationRemoveAllFollowingRequest represents the request body for admin/federation/remove-all-following.
type FederationRemoveAllFollowingRequest struct {
	Host *string `json:"host"`
}

// FederationRemoveAllFollowing calls /admin/federation/remove-all-following (authenticated).
func (s *Service) FederationRemoveAllFollowing(ctx context.Context, req *FederationRemoveAllFollowingRequest) error {
	return s.cli.Do(ctx, "/admin/federation/remove-all-following", req, nil)
}

// QueueRetryJobRequest represents the request body for admin/queue/retry-job.
type QueueRetryJobRequest struct {
	Queue *string `json:"queue"`
	JobId *string `json:"jobId"`
}

// QueueRetryJob calls /admin/queue/retry-job (authenticated).
func (s *Service) QueueRetryJob(ctx context.Context, req *QueueRetryJobRequest) error {
	return s.cli.Do(ctx, "/admin/queue/retry-job", req, nil)
}

// SystemWebhookShowRequest represents the request body for admin/system-webhook/show.
type SystemWebhookShowRequest struct {
	Id *types.ID `json:"id"`
}

// SystemWebhookShow calls /admin/system-webhook/show (authenticated).
func (s *Service) SystemWebhookShow(ctx context.Context, req *SystemWebhookShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/system-webhook/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// QueueClearRequest represents the request body for admin/queue/clear.
type QueueClearRequest struct {
	State *string `json:"state"`
	Queue *string `json:"queue"`
}

// QueueClear calls /admin/queue/clear (authenticated).
func (s *Service) QueueClear(ctx context.Context, req *QueueClearRequest) error {
	return s.cli.Do(ctx, "/admin/queue/clear", req, nil)
}

// QueueShowJobLogsRequest represents the request body for admin/queue/show-job-logs.
type QueueShowJobLogsRequest struct {
	Queue *string `json:"queue"`
	JobId *string `json:"jobId"`
}

// QueueShowJobLogs calls /admin/queue/show-job-logs (authenticated).
func (s *Service) QueueShowJobLogs(ctx context.Context, req *QueueShowJobLogsRequest) ([]string, error) {
	var resp []string
	if err := s.cli.Do(ctx, "/admin/queue/show-job-logs", req, &resp); err != nil {
		return *new([]string), err
	}
	return resp, nil
}

// ShowUsersRequest represents the request body for admin/show-users.
type ShowUsersRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Sort *string `json:"sort,omitempty"`
	State *string `json:"state,omitempty"`
	Origin *string `json:"origin,omitempty"`
	Username *string `json:"username,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
}

// ShowUsers calls /admin/show-users (authenticated).
func (s *Service) ShowUsers(ctx context.Context, req *ShowUsersRequest) ([]types.UserDetailed, error) {
	var resp []types.UserDetailed
	if err := s.cli.Do(ctx, "/admin/show-users", req, &resp); err != nil {
		return *new([]types.UserDetailed), err
	}
	return resp, nil
}

// AbuseReportNotificationRecipientUpdateRequest represents the request body for admin/abuse-report/notification-recipient/update.
type AbuseReportNotificationRecipientUpdateRequest struct {
	SystemWebhookId *types.ID `json:"systemWebhookId,omitempty"`
	Id *types.ID `json:"id"`
	IsActive *bool `json:"isActive"`
	Name *string `json:"name"`
	Method *string `json:"method"`
	UserId *types.ID `json:"userId,omitempty"`
}

// AbuseReportNotificationRecipientUpdate calls /admin/abuse-report/notification-recipient/update (authenticated).
func (s *Service) AbuseReportNotificationRecipientUpdate(ctx context.Context, req *AbuseReportNotificationRecipientUpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/abuse-report/notification-recipient/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// EmojiSetCategoryBulkRequest represents the request body for admin/emoji/set-category-bulk.
type EmojiSetCategoryBulkRequest struct {
	Ids []types.ID `json:"ids"`
	Category *string `json:"category,omitempty"`
}

// EmojiSetCategoryBulk calls /admin/emoji/set-category-bulk (authenticated).
func (s *Service) EmojiSetCategoryBulk(ctx context.Context, req *EmojiSetCategoryBulkRequest) error {
	return s.cli.Do(ctx, "/admin/emoji/set-category-bulk", req, nil)
}

// SystemWebhookCreateRequest represents the request body for admin/system-webhook/create.
type SystemWebhookCreateRequest struct {
	Secret *string `json:"secret,omitempty"`
	IsActive *bool `json:"isActive"`
	Name *string `json:"name"`
	On []string `json:"on"`
	Url *string `json:"url"`
}

// SystemWebhookCreate calls /admin/system-webhook/create (authenticated).
func (s *Service) SystemWebhookCreate(ctx context.Context, req *SystemWebhookCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/system-webhook/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// QueueShowJobRequest represents the request body for admin/queue/show-job.
type QueueShowJobRequest struct {
	Queue *string `json:"queue"`
	JobId *string `json:"jobId"`
}

// QueueShowJob calls /admin/queue/show-job (authenticated).
func (s *Service) QueueShowJob(ctx context.Context, req *QueueShowJobRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/queue/show-job", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// AbuseReportNotificationRecipientCreateRequest represents the request body for admin/abuse-report/notification-recipient/create.
type AbuseReportNotificationRecipientCreateRequest struct {
	SystemWebhookId *types.ID `json:"systemWebhookId,omitempty"`
	IsActive *bool `json:"isActive"`
	Name *string `json:"name"`
	Method *string `json:"method"`
	UserId *types.ID `json:"userId,omitempty"`
}

// AbuseReportNotificationRecipientCreate calls /admin/abuse-report/notification-recipient/create (authenticated).
func (s *Service) AbuseReportNotificationRecipientCreate(ctx context.Context, req *AbuseReportNotificationRecipientCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/abuse-report/notification-recipient/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UpdateProxyAccountRequest represents the request body for admin/update-proxy-account.
type UpdateProxyAccountRequest struct {
	Description *string `json:"description,omitempty"`
}

// UpdateProxyAccount calls /admin/update-proxy-account (authenticated).
func (s *Service) UpdateProxyAccount(ctx context.Context, req *UpdateProxyAccountRequest) (types.UserDetailed, error) {
	var resp types.UserDetailed
	if err := s.cli.Do(ctx, "/admin/update-proxy-account", req, &resp); err != nil {
		return *new(types.UserDetailed), err
	}
	return resp, nil
}

// DeleteAllFilesOfAUserRequest represents the request body for admin/delete-all-files-of-a-user.
type DeleteAllFilesOfAUserRequest struct {
	UserId *types.ID `json:"userId"`
}

// DeleteAllFilesOfAUser calls /admin/delete-all-files-of-a-user (authenticated).
func (s *Service) DeleteAllFilesOfAUser(ctx context.Context, req *DeleteAllFilesOfAUserRequest) error {
	return s.cli.Do(ctx, "/admin/delete-all-files-of-a-user", req, nil)
}

// SystemWebhookTestRequest represents the request body for admin/system-webhook/test.
type SystemWebhookTestRequest struct {
	WebhookId *types.ID `json:"webhookId"`
	Type *string `json:"type"`
	Override any `json:"override,omitempty"`
}

// SystemWebhookTest calls /admin/system-webhook/test (authenticated).
func (s *Service) SystemWebhookTest(ctx context.Context, req *SystemWebhookTestRequest) error {
	return s.cli.Do(ctx, "/admin/system-webhook/test", req, nil)
}

// FederationUpdateInstanceRequest represents the request body for admin/federation/update-instance.
type FederationUpdateInstanceRequest struct {
	IsSuspended *bool `json:"isSuspended,omitempty"`
	ModerationNote *string `json:"moderationNote,omitempty"`
	Host *string `json:"host"`
}

// FederationUpdateInstance calls /admin/federation/update-instance (authenticated).
func (s *Service) FederationUpdateInstance(ctx context.Context, req *FederationUpdateInstanceRequest) error {
	return s.cli.Do(ctx, "/admin/federation/update-instance", req, nil)
}

// ForwardAbuseUserReportRequest represents the request body for admin/forward-abuse-user-report.
type ForwardAbuseUserReportRequest struct {
	ReportId *types.ID `json:"reportId"`
}

// ForwardAbuseUserReport calls /admin/forward-abuse-user-report (authenticated).
func (s *Service) ForwardAbuseUserReport(ctx context.Context, req *ForwardAbuseUserReportRequest) error {
	return s.cli.Do(ctx, "/admin/forward-abuse-user-report", req, nil)
}

// ShowModerationLogsRequest represents the request body for admin/show-moderation-logs.
type ShowModerationLogsRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Type *string `json:"type,omitempty"`
	UserId *types.ID `json:"userId,omitempty"`
	Search *string `json:"search,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// ShowModerationLogs calls /admin/show-moderation-logs (authenticated).
func (s *Service) ShowModerationLogs(ctx context.Context, req *ShowModerationLogsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/show-moderation-logs", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// RelaysList calls /admin/relays/list (authenticated).
func (s *Service) RelaysList(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/relays/list", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// AvatarDecorationsCreateRequest represents the request body for admin/avatar-decorations/create.
type AvatarDecorationsCreateRequest struct {
	Url *string `json:"url"`
	RoleIdsThatCanBeUsedThisDecoration []string `json:"roleIdsThatCanBeUsedThisDecoration,omitempty"`
	Category *string `json:"category,omitempty"`
	Name *string `json:"name"`
	Description *string `json:"description"`
}

// AvatarDecorationsCreate calls /admin/avatar-decorations/create (authenticated).
func (s *Service) AvatarDecorationsCreate(ctx context.Context, req *AvatarDecorationsCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/avatar-decorations/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// SystemWebhookListRequest represents the request body for admin/system-webhook/list.
type SystemWebhookListRequest struct {
	On []string `json:"on,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
}

// SystemWebhookList calls /admin/system-webhook/list (authenticated).
func (s *Service) SystemWebhookList(ctx context.Context, req *SystemWebhookListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/system-webhook/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// Retention calls /retention.
func (s *Service) Retention(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/retention", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// GetIndexStats calls /admin/get-index-stats (authenticated).
func (s *Service) GetIndexStats(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/get-index-stats", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// AbuseReportNotificationRecipientDeleteRequest represents the request body for admin/abuse-report/notification-recipient/delete.
type AbuseReportNotificationRecipientDeleteRequest struct {
	Id *types.ID `json:"id"`
}

// AbuseReportNotificationRecipientDelete calls /admin/abuse-report/notification-recipient/delete (authenticated).
func (s *Service) AbuseReportNotificationRecipientDelete(ctx context.Context, req *AbuseReportNotificationRecipientDeleteRequest) error {
	return s.cli.Do(ctx, "/admin/abuse-report/notification-recipient/delete", req, nil)
}

// EmojiListRemoteRequest represents the request body for admin/emoji/list-remote.
type EmojiListRemoteRequest struct {
	Query *string `json:"query,omitempty"`
	Host *string `json:"host,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// EmojiListRemote calls /admin/emoji/list-remote (authenticated).
func (s *Service) EmojiListRemote(ctx context.Context, req *EmojiListRemoteRequest) ([]types.EmojiDetailed, error) {
	var resp []types.EmojiDetailed
	if err := s.cli.Do(ctx, "/admin/emoji/list-remote", req, &resp); err != nil {
		return *new([]types.EmojiDetailed), err
	}
	return resp, nil
}

// AbuseReportNotificationRecipientShowRequest represents the request body for admin/abuse-report/notification-recipient/show.
type AbuseReportNotificationRecipientShowRequest struct {
	Id *types.ID `json:"id"`
}

// AbuseReportNotificationRecipientShow calls /admin/abuse-report/notification-recipient/show (authenticated).
func (s *Service) AbuseReportNotificationRecipientShow(ctx context.Context, req *AbuseReportNotificationRecipientShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/abuse-report/notification-recipient/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// QueuePromoteJobsRequest represents the request body for admin/queue/promote-jobs.
type QueuePromoteJobsRequest struct {
	Queue *string `json:"queue"`
}

// QueuePromoteJobs calls /admin/queue/promote-jobs (authenticated).
func (s *Service) QueuePromoteJobs(ctx context.Context, req *QueuePromoteJobsRequest) error {
	return s.cli.Do(ctx, "/admin/queue/promote-jobs", req, nil)
}

// ServerInfo calls /admin/server-info (authenticated).
func (s *Service) ServerInfo(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/server-info", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// AbuseReportNotificationRecipientListRequest represents the request body for admin/abuse-report/notification-recipient/list.
type AbuseReportNotificationRecipientListRequest struct {
	Method []string `json:"method,omitempty"`
}

// AbuseReportNotificationRecipientList calls /admin/abuse-report/notification-recipient/list (authenticated).
func (s *Service) AbuseReportNotificationRecipientList(ctx context.Context, req *AbuseReportNotificationRecipientListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/abuse-report/notification-recipient/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// QueueQueues calls /admin/queue/queues (authenticated).
func (s *Service) QueueQueues(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/queue/queues", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// QueueInboxDelayed calls /admin/queue/inbox-delayed (authenticated).
func (s *Service) QueueInboxDelayed(ctx context.Context) ([][]any, error) {
	var resp [][]any
	if err := s.cli.Do(ctx, "/admin/queue/inbox-delayed", nil, &resp); err != nil {
		return *new([][]any), err
	}
	return resp, nil
}

// RolesUpdateRequest represents the request body for admin/roles/update.
type RolesUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	Color *string `json:"color,omitempty"`
	Target *string `json:"target,omitempty"`
	IsPublic *bool `json:"isPublic,omitempty"`
	DisplayOrder *int64 `json:"displayOrder,omitempty"`
	Policies any `json:"policies,omitempty"`
	Name *string `json:"name,omitempty"`
	IconUrl *string `json:"iconUrl,omitempty"`
	CondFormula any `json:"condFormula,omitempty"`
	IsModerator *bool `json:"isModerator,omitempty"`
	IsExplorable *bool `json:"isExplorable,omitempty"`
	AsBadge *bool `json:"asBadge,omitempty"`
	IsAdministrator *bool `json:"isAdministrator,omitempty"`
	PreserveAssignmentOnMoveAccount *bool `json:"preserveAssignmentOnMoveAccount,omitempty"`
	CanEditMembersByModerator *bool `json:"canEditMembersByModerator,omitempty"`
	RoleId *types.ID `json:"roleId"`
}

// RolesUpdate calls /admin/roles/update (authenticated).
func (s *Service) RolesUpdate(ctx context.Context, req *RolesUpdateRequest) error {
	return s.cli.Do(ctx, "/admin/roles/update", req, nil)
}

// AvatarDecorationsDeleteRequest represents the request body for admin/avatar-decorations/delete.
type AvatarDecorationsDeleteRequest struct {
	Id *types.ID `json:"id"`
}

// AvatarDecorationsDelete calls /admin/avatar-decorations/delete (authenticated).
func (s *Service) AvatarDecorationsDelete(ctx context.Context, req *AvatarDecorationsDeleteRequest) error {
	return s.cli.Do(ctx, "/admin/avatar-decorations/delete", req, nil)
}

// AvatarDecorationsListRequest represents the request body for admin/avatar-decorations/list.
type AvatarDecorationsListRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	UserId *types.ID `json:"userId,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// AvatarDecorationsList calls /admin/avatar-decorations/list (authenticated).
func (s *Service) AvatarDecorationsList(ctx context.Context, req *AvatarDecorationsListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/admin/avatar-decorations/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ResetPasswordRequest represents the request body for admin/reset-password.
type ResetPasswordRequest struct {
	UserId *types.ID `json:"userId"`
}

// ResetPassword calls /admin/reset-password (authenticated).
func (s *Service) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/reset-password", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// DeleteAccountRequest represents the request body for admin/delete-account.
type DeleteAccountRequest struct {
	UserId *types.ID `json:"userId"`
}

// DeleteAccount calls /admin/delete-account (authenticated).
func (s *Service) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) error {
	return s.cli.Do(ctx, "/admin/delete-account", req, nil)
}

// EmojiRemoveAliasesBulkRequest represents the request body for admin/emoji/remove-aliases-bulk.
type EmojiRemoveAliasesBulkRequest struct {
	Ids []types.ID `json:"ids"`
	Aliases []string `json:"aliases"`
}

// EmojiRemoveAliasesBulk calls /admin/emoji/remove-aliases-bulk (authenticated).
func (s *Service) EmojiRemoveAliasesBulk(ctx context.Context, req *EmojiRemoveAliasesBulkRequest) error {
	return s.cli.Do(ctx, "/admin/emoji/remove-aliases-bulk", req, nil)
}

// QueueQueueStatsRequest represents the request body for admin/queue/queue-stats.
type QueueQueueStatsRequest struct {
	Queue *string `json:"queue"`
}

// QueueQueueStats calls /admin/queue/queue-stats (authenticated).
func (s *Service) QueueQueueStats(ctx context.Context, req *QueueQueueStatsRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/admin/queue/queue-stats", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UnsetUserBannerRequest represents the request body for admin/unset-user-banner.
type UnsetUserBannerRequest struct {
	UserId *types.ID `json:"userId"`
}

// UnsetUserBanner calls /admin/unset-user-banner (authenticated).
func (s *Service) UnsetUserBanner(ctx context.Context, req *UnsetUserBannerRequest) error {
	return s.cli.Do(ctx, "/admin/unset-user-banner", req, nil)
}

// AvatarDecorationsUpdateRequest represents the request body for admin/avatar-decorations/update.
type AvatarDecorationsUpdateRequest struct {
	Category *string `json:"category,omitempty"`
	Id *types.ID `json:"id"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Url *string `json:"url,omitempty"`
	RoleIdsThatCanBeUsedThisDecoration []string `json:"roleIdsThatCanBeUsedThisDecoration,omitempty"`
}

// AvatarDecorationsUpdate calls /admin/avatar-decorations/update (authenticated).
func (s *Service) AvatarDecorationsUpdate(ctx context.Context, req *AvatarDecorationsUpdateRequest) error {
	return s.cli.Do(ctx, "/admin/avatar-decorations/update", req, nil)
}

// AdminEmojiListRequest represents the request body for v2/admin/emoji/list.
type AdminEmojiListRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Page *int64 `json:"page,omitempty"`
	SortKeys []string `json:"sortKeys,omitempty"`
	Query any `json:"query,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// AdminEmojiList calls /v2/admin/emoji/list (authenticated).
func (s *Service) AdminEmojiList(ctx context.Context, req *AdminEmojiListRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/v2/admin/emoji/list", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

