// Code generated by tools/gen/main.go. DO NOT EDIT.

package ap

import "context"

// Service provides ap-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new ApService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// GetRequest represents the request body for ap/get.
type GetRequest struct {
	Uri *string `json:"uri"`
}

// Get calls /ap/get (authenticated).
func (s *Service) Get(ctx context.Context, req *GetRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/ap/get", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ShowRequest represents the request body for ap/show.
type ShowRequest struct {
	Uri *string `json:"uri"`
}

// Show calls /ap/show (authenticated).
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/ap/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

