// Code generated by tools/gen/main.go. DO NOT EDIT.

package flash

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides flash-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new FlashService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// UpdateRequest represents the request body for flash/update.
type UpdateRequest struct {
	Summary *string `json:"summary,omitempty"`
	Script *string `json:"script,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
	FlashId *types.ID `json:"flashId"`
	Title *string `json:"title,omitempty"`
}

// Update calls /flash/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) error {
	return s.cli.Do(ctx, "/flash/update", req, nil)
}

// UnlikeRequest represents the request body for flash/unlike.
type UnlikeRequest struct {
	FlashId *types.ID `json:"flashId"`
}

// Unlike calls /flash/unlike (authenticated).
func (s *Service) Unlike(ctx context.Context, req *UnlikeRequest) error {
	return s.cli.Do(ctx, "/flash/unlike", req, nil)
}

// CreateRequest represents the request body for flash/create.
type CreateRequest struct {
	Script *string `json:"script"`
	Permissions []string `json:"permissions"`
	Visibility *string `json:"visibility,omitempty"`
	Title *string `json:"title"`
	Summary *string `json:"summary"`
}

// Create calls /flash/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/flash/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// DeleteRequest represents the request body for flash/delete.
type DeleteRequest struct {
	FlashId *types.ID `json:"flashId"`
}

// Delete calls /flash/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/flash/delete", req, nil)
}

// MyLikesRequest represents the request body for flash/my-likes.
type MyLikesRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	Search *string `json:"search,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// MyLikes calls /flash/my-likes (authenticated).
func (s *Service) MyLikes(ctx context.Context, req *MyLikesRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/flash/my-likes", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// SearchRequest represents the request body for flash/search.
type SearchRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Query *string `json:"query"`
}

// Search calls /flash/search.
func (s *Service) Search(ctx context.Context, req *SearchRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/flash/search", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// MyRequest represents the request body for flash/my.
type MyRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// My calls /flash/my (authenticated).
func (s *Service) My(ctx context.Context, req *MyRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/flash/my", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// FeaturedRequest represents the request body for flash/featured.
type FeaturedRequest struct {
	Offset *int64 `json:"offset,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Featured calls /flash/featured.
func (s *Service) Featured(ctx context.Context, req *FeaturedRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/flash/featured", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// LikeRequest represents the request body for flash/like.
type LikeRequest struct {
	FlashId *types.ID `json:"flashId"`
}

// Like calls /flash/like (authenticated).
func (s *Service) Like(ctx context.Context, req *LikeRequest) error {
	return s.cli.Do(ctx, "/flash/like", req, nil)
}

// ShowRequest represents the request body for flash/show.
type ShowRequest struct {
	FlashId *types.ID `json:"flashId"`
}

// Show calls /flash/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/flash/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

