// Code generated by tools/gen/main.go. DO NOT EDIT.

package invite

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides invite-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new InviteService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ListRequest represents the request body for invite/list.
type ListRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// List calls /invite/list (authenticated).
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/invite/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// DeleteRequest represents the request body for invite/delete.
type DeleteRequest struct {
	InviteId *types.ID `json:"inviteId"`
}

// Delete calls /invite/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/invite/delete", req, nil)
}

// Limit calls /invite/limit (authenticated).
func (s *Service) Limit(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/invite/limit", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// Create calls /invite/create (authenticated).
func (s *Service) Create(ctx context.Context) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/invite/create", nil, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

