// Code generated by tools/gen/main.go. DO NOT EDIT.

package username

import "context"

// Service provides username-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new UsernameService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// AvailableRequest represents the request body for username/available.
type AvailableRequest struct {
	Username *string `json:"username"`
}

// Available calls /username/available.
func (s *Service) Available(ctx context.Context, req *AvailableRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/username/available", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

