// Code generated by tools/gen/main.go. DO NOT EDIT.

package notes

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// DraftsUpdateRequest represents the request body for notes/drafts/update.
type DraftsUpdateRequest struct {
	LocalOnly *bool `json:"localOnly,omitempty"`
	FileIds []types.ID `json:"fileIds,omitempty"`
	Poll any `json:"poll,omitempty"`
	DraftId *types.ID `json:"draftId"`
	VisibleUserIds []types.ID `json:"visibleUserIds,omitempty"`
	ReactionAcceptance *string `json:"reactionAcceptance,omitempty"`
	ReplyId *types.ID `json:"replyId,omitempty"`
	RenoteId *types.ID `json:"renoteId,omitempty"`
	Cw *string `json:"cw,omitempty"`
	Text *string `json:"text,omitempty"`
	ScheduledAt *int64 `json:"scheduledAt,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
	Hashtag *string `json:"hashtag,omitempty"`
	ChannelId *types.ID `json:"channelId,omitempty"`
	IsActuallyScheduled *bool `json:"isActuallyScheduled,omitempty"`
}

// DraftsUpdate calls /notes/drafts/update (authenticated).
func (s *Service) DraftsUpdate(ctx context.Context, req *DraftsUpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/notes/drafts/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ClipsRequest represents the request body for notes/clips.
type ClipsRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// Clips calls /notes/clips.
func (s *Service) Clips(ctx context.Context, req *ClipsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/notes/clips", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// RepliesRequest represents the request body for notes/replies.
type RepliesRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	NoteId *types.ID `json:"noteId"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// Replies calls /notes/replies.
func (s *Service) Replies(ctx context.Context, req *RepliesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/replies", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// UserListTimelineRequest represents the request body for notes/user-list-timeline.
type UserListTimelineRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	AllowPartial *bool `json:"allowPartial,omitempty"`
	IncludeMyRenotes *bool `json:"includeMyRenotes,omitempty"`
	IncludeRenotedMyNotes *bool `json:"includeRenotedMyNotes,omitempty"`
	IncludeLocalRenotes *bool `json:"includeLocalRenotes,omitempty"`
	WithRenotes *bool `json:"withRenotes,omitempty"`
	WithFiles *bool `json:"withFiles,omitempty"`
	ListId *types.ID `json:"listId"`
}

// UserListTimeline calls /notes/user-list-timeline (authenticated).
func (s *Service) UserListTimeline(ctx context.Context, req *UserListTimelineRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/user-list-timeline", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// MentionsRequest represents the request body for notes/mentions.
type MentionsRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
	Following *bool `json:"following,omitempty"`
}

// Mentions calls /notes/mentions (authenticated).
func (s *Service) Mentions(ctx context.Context, req *MentionsRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/mentions", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// ConversationRequest represents the request body for notes/conversation.
type ConversationRequest struct {
	NoteId *types.ID `json:"noteId"`
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Conversation calls /notes/conversation.
func (s *Service) Conversation(ctx context.Context, req *ConversationRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/conversation", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// PollsVoteRequest represents the request body for notes/polls/vote.
type PollsVoteRequest struct {
	NoteId *types.ID `json:"noteId"`
	Choice *int64 `json:"choice"`
}

// PollsVote calls /notes/polls/vote (authenticated).
func (s *Service) PollsVote(ctx context.Context, req *PollsVoteRequest) error {
	return s.cli.Do(ctx, "/notes/polls/vote", req, nil)
}

// ShowPartialBulkRequest represents the request body for notes/show-partial-bulk.
type ShowPartialBulkRequest struct {
	NoteIds []types.ID `json:"noteIds"`
}

// ShowPartialBulk calls /notes/show-partial-bulk.
func (s *Service) ShowPartialBulk(ctx context.Context, req *ShowPartialBulkRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/notes/show-partial-bulk", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// RenotesRequest represents the request body for notes/renotes.
type RenotesRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	NoteId *types.ID `json:"noteId"`
	Limit *int64 `json:"limit,omitempty"`
}

// Renotes calls /notes/renotes.
func (s *Service) Renotes(ctx context.Context, req *RenotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/renotes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// FavoritesDeleteRequest represents the request body for notes/favorites/delete.
type FavoritesDeleteRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// FavoritesDelete calls /notes/favorites/delete (authenticated).
func (s *Service) FavoritesDelete(ctx context.Context, req *FavoritesDeleteRequest) error {
	return s.cli.Do(ctx, "/notes/favorites/delete", req, nil)
}

// ThreadMutingCreateRequest represents the request body for notes/thread-muting/create.
type ThreadMutingCreateRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// ThreadMutingCreate calls /notes/thread-muting/create (authenticated).
func (s *Service) ThreadMutingCreate(ctx context.Context, req *ThreadMutingCreateRequest) error {
	return s.cli.Do(ctx, "/notes/thread-muting/create", req, nil)
}

// DraftsDeleteRequest represents the request body for notes/drafts/delete.
type DraftsDeleteRequest struct {
	DraftId *types.ID `json:"draftId"`
}

// DraftsDelete calls /notes/drafts/delete (authenticated).
func (s *Service) DraftsDelete(ctx context.Context, req *DraftsDeleteRequest) error {
	return s.cli.Do(ctx, "/notes/drafts/delete", req, nil)
}

// DraftsListRequest represents the request body for notes/drafts/list.
type DraftsListRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Scheduled *bool `json:"scheduled,omitempty"`
}

// DraftsList calls /notes/drafts/list (authenticated).
func (s *Service) DraftsList(ctx context.Context, req *DraftsListRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/drafts/list", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// PollsRecommendationRequest represents the request body for notes/polls/recommendation.
type PollsRecommendationRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	ExcludeChannels *bool `json:"excludeChannels,omitempty"`
}

// PollsRecommendation calls /notes/polls/recommendation (authenticated).
func (s *Service) PollsRecommendation(ctx context.Context, req *PollsRecommendationRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/polls/recommendation", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// ChildrenRequest represents the request body for notes/children.
type ChildrenRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	NoteId *types.ID `json:"noteId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// Children calls /notes/children.
func (s *Service) Children(ctx context.Context, req *ChildrenRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/children", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// FeaturedRequest represents the request body for notes/featured.
type FeaturedRequest struct {
	ChannelId *types.ID `json:"channelId,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// Featured calls /notes/featured.
func (s *Service) Featured(ctx context.Context, req *FeaturedRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/featured", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// TranslateRequest represents the request body for notes/translate.
type TranslateRequest struct {
	NoteId *types.ID `json:"noteId"`
	TargetLang *string `json:"targetLang"`
}

// Translate calls /notes/translate (authenticated).
func (s *Service) Translate(ctx context.Context, req *TranslateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/notes/translate", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// FavoritesCreateRequest represents the request body for notes/favorites/create.
type FavoritesCreateRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// FavoritesCreate calls /notes/favorites/create (authenticated).
func (s *Service) FavoritesCreate(ctx context.Context, req *FavoritesCreateRequest) error {
	return s.cli.Do(ctx, "/notes/favorites/create", req, nil)
}

// DraftsCount calls /notes/drafts/count (authenticated).
func (s *Service) DraftsCount(ctx context.Context) (int64, error) {
	var resp int64
	if err := s.cli.Do(ctx, "/notes/drafts/count", nil, &resp); err != nil {
		return *new(int64), err
	}
	return resp, nil
}

// SearchByTagRequest represents the request body for notes/search-by-tag.
type SearchByTagRequest struct {
	Tag *string `json:"tag"`
	Query [][]string `json:"query"`
	Reply *bool `json:"reply,omitempty"`
	WithFiles *bool `json:"withFiles,omitempty"`
	Poll *bool `json:"poll,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Renote *bool `json:"renote,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// SearchByTag calls /notes/search-by-tag.
func (s *Service) SearchByTag(ctx context.Context, req *SearchByTagRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes/search-by-tag", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// DraftsCreateRequest represents the request body for notes/drafts/create.
type DraftsCreateRequest struct {
	Cw *string `json:"cw,omitempty"`
	ReactionAcceptance *string `json:"reactionAcceptance,omitempty"`
	ChannelId *types.ID `json:"channelId,omitempty"`
	Poll any `json:"poll,omitempty"`
	ScheduledAt *int64 `json:"scheduledAt,omitempty"`
	IsActuallyScheduled *bool `json:"isActuallyScheduled,omitempty"`
	Visibility *string `json:"visibility,omitempty"`
	VisibleUserIds []types.ID `json:"visibleUserIds,omitempty"`
	Hashtag *string `json:"hashtag,omitempty"`
	LocalOnly *bool `json:"localOnly,omitempty"`
	ReplyId *types.ID `json:"replyId,omitempty"`
	RenoteId *types.ID `json:"renoteId,omitempty"`
	Text *string `json:"text,omitempty"`
	FileIds []types.ID `json:"fileIds,omitempty"`
}

// DraftsCreate calls /notes/drafts/create (authenticated).
func (s *Service) DraftsCreate(ctx context.Context, req *DraftsCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/notes/drafts/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ReactionsRequest represents the request body for notes/reactions.
type ReactionsRequest struct {
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	NoteId *types.ID `json:"noteId"`
	Type *string `json:"type,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
}

// Reactions calls /notes/reactions.
func (s *Service) Reactions(ctx context.Context, req *ReactionsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/notes/reactions", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// StateRequest represents the request body for notes/state.
type StateRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// State calls /notes/state (authenticated).
func (s *Service) State(ctx context.Context, req *StateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/notes/state", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UnrenoteRequest represents the request body for notes/unrenote.
type UnrenoteRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// Unrenote calls /notes/unrenote (authenticated).
func (s *Service) Unrenote(ctx context.Context, req *UnrenoteRequest) error {
	return s.cli.Do(ctx, "/notes/unrenote", req, nil)
}

// ThreadMutingDeleteRequest represents the request body for notes/thread-muting/delete.
type ThreadMutingDeleteRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// ThreadMutingDelete calls /notes/thread-muting/delete (authenticated).
func (s *Service) ThreadMutingDelete(ctx context.Context, req *ThreadMutingDeleteRequest) error {
	return s.cli.Do(ctx, "/notes/thread-muting/delete", req, nil)
}

// NotesRequest represents the request body for notes.
type NotesRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Local *bool `json:"local,omitempty"`
	Reply *bool `json:"reply,omitempty"`
	WithFiles *bool `json:"withFiles,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	Renote *bool `json:"renote,omitempty"`
	Poll *bool `json:"poll,omitempty"`
}

// Notes calls /notes.
func (s *Service) Notes(ctx context.Context, req *NotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

