// Code generated by tools/gen/main.go. DO NOT EDIT.

package bubblegame

import "context"

// Service provides bubblegame-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new BubblegameService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// RegisterRequest represents the request body for bubble-game/register.
type RegisterRequest struct {
	GameVersion *int64 `json:"gameVersion"`
	Score *int64 `json:"score"`
	Seed *string `json:"seed"`
	Logs [][]int64 `json:"logs"`
	GameMode *string `json:"gameMode"`
}

// Register calls /bubble-game/register (authenticated).
func (s *Service) Register(ctx context.Context, req *RegisterRequest) error {
	return s.cli.Do(ctx, "/bubble-game/register", req, nil)
}

// RankingRequest represents the request body for bubble-game/ranking.
type RankingRequest struct {
	GameMode *string `json:"gameMode"`
}

// Ranking calls /bubble-game/ranking.
func (s *Service) Ranking(ctx context.Context, req *RankingRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/bubble-game/ranking", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

