// Code generated by tools/gen/main.go. DO NOT EDIT.

package pages

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides pages-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new PagesService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// PagePushRequest represents the request body for page-push.
type PagePushRequest struct {
	PageId *types.ID `json:"pageId"`
	Event *string `json:"event"`
	Var any `json:"var,omitempty"`
}

// PagePush calls /page-push (authenticated).
func (s *Service) PagePush(ctx context.Context, req *PagePushRequest) error {
	return s.cli.Do(ctx, "/page-push", req, nil)
}

// UnlikeRequest represents the request body for pages/unlike.
type UnlikeRequest struct {
	PageId *types.ID `json:"pageId"`
}

// Unlike calls /pages/unlike (authenticated).
func (s *Service) Unlike(ctx context.Context, req *UnlikeRequest) error {
	return s.cli.Do(ctx, "/pages/unlike", req, nil)
}

// LikeRequest represents the request body for pages/like.
type LikeRequest struct {
	PageId *types.ID `json:"pageId"`
}

// Like calls /pages/like (authenticated).
func (s *Service) Like(ctx context.Context, req *LikeRequest) error {
	return s.cli.Do(ctx, "/pages/like", req, nil)
}

// DeleteRequest represents the request body for pages/delete.
type DeleteRequest struct {
	PageId *types.ID `json:"pageId"`
}

// Delete calls /pages/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/pages/delete", req, nil)
}

// CreateRequest represents the request body for pages/create.
type CreateRequest struct {
	Variables []any `json:"variables"`
	EyeCatchingImageId *types.ID `json:"eyeCatchingImageId,omitempty"`
	Font *string `json:"font,omitempty"`
	Name *string `json:"name"`
	Summary *string `json:"summary,omitempty"`
	Script *string `json:"script"`
	AlignCenter *bool `json:"alignCenter,omitempty"`
	HideTitleWhenPinned *bool `json:"hideTitleWhenPinned,omitempty"`
	Title *string `json:"title"`
	Content []any `json:"content"`
}

// Create calls /pages/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) (types.Page, error) {
	var resp types.Page
	if err := s.cli.Do(ctx, "/pages/create", req, &resp); err != nil {
		return *new(types.Page), err
	}
	return resp, nil
}

// UpdateRequest represents the request body for pages/update.
type UpdateRequest struct {
	EyeCatchingImageId *types.ID `json:"eyeCatchingImageId,omitempty"`
	Font *string `json:"font,omitempty"`
	AlignCenter *bool `json:"alignCenter,omitempty"`
	PageId *types.ID `json:"pageId"`
	Title *string `json:"title,omitempty"`
	Script *string `json:"script,omitempty"`
	HideTitleWhenPinned *bool `json:"hideTitleWhenPinned,omitempty"`
	Name *string `json:"name,omitempty"`
	Summary *string `json:"summary,omitempty"`
	Content []any `json:"content,omitempty"`
	Variables []any `json:"variables,omitempty"`
}

// Update calls /pages/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) error {
	return s.cli.Do(ctx, "/pages/update", req, nil)
}

// Featured calls /pages/featured.
func (s *Service) Featured(ctx context.Context) ([]types.Page, error) {
	var resp []types.Page
	if err := s.cli.Do(ctx, "/pages/featured", nil, &resp); err != nil {
		return *new([]types.Page), err
	}
	return resp, nil
}

// ShowRequest represents the request body for pages/show.
type ShowRequest struct {
	PageId *types.ID `json:"pageId"`
	Name *string `json:"name"`
	Username *string `json:"username"`
}

// Show calls /pages/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (types.Page, error) {
	var resp types.Page
	if err := s.cli.Do(ctx, "/pages/show", req, &resp); err != nil {
		return *new(types.Page), err
	}
	return resp, nil
}

