// Code generated by tools/gen/main.go. DO NOT EDIT.

package users

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// ListsListRequest represents the request body for users/lists/list.
type ListsListRequest struct {
	UserId *types.ID `json:"userId,omitempty"`
}

// ListsList calls /users/lists/list.
func (s *Service) ListsList(ctx context.Context, req *ListsListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/lists/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// NotesRequest represents the request body for users/notes.
type NotesRequest struct {
	UserId *types.ID `json:"userId"`
	WithReplies *bool `json:"withReplies,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	WithRenotes *bool `json:"withRenotes,omitempty"`
	WithChannelNotes *bool `json:"withChannelNotes,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	AllowPartial *bool `json:"allowPartial,omitempty"`
	WithFiles *bool `json:"withFiles,omitempty"`
}

// Notes calls /users/notes.
func (s *Service) Notes(ctx context.Context, req *NotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/users/notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// ReportAbuseRequest represents the request body for users/report-abuse.
type ReportAbuseRequest struct {
	UserId *types.ID `json:"userId"`
	Comment *string `json:"comment"`
}

// ReportAbuse calls /users/report-abuse (authenticated).
func (s *Service) ReportAbuse(ctx context.Context, req *ReportAbuseRequest) error {
	return s.cli.Do(ctx, "/users/report-abuse", req, nil)
}

// ListsUpdateRequest represents the request body for users/lists/update.
type ListsUpdateRequest struct {
	IsPublic *bool `json:"isPublic,omitempty"`
	ListId *types.ID `json:"listId"`
	Name *string `json:"name,omitempty"`
}

// ListsUpdate calls /users/lists/update (authenticated).
func (s *Service) ListsUpdate(ctx context.Context, req *ListsUpdateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/users/lists/update", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// FeaturedNotesRequest represents the request body for users/featured-notes.
type FeaturedNotesRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	UserId *types.ID `json:"userId"`
}

// FeaturedNotes calls /users/featured-notes.
func (s *Service) FeaturedNotes(ctx context.Context, req *FeaturedNotesRequest) ([]types.Note, error) {
	var resp []types.Note
	if err := s.cli.Do(ctx, "/users/featured-notes", req, &resp); err != nil {
		return *new([]types.Note), err
	}
	return resp, nil
}

// GetFrequentlyRepliedUsersRequest represents the request body for users/get-frequently-replied-users.
type GetFrequentlyRepliedUsersRequest struct {
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
}

// GetFrequentlyRepliedUsers calls /users/get-frequently-replied-users.
func (s *Service) GetFrequentlyRepliedUsers(ctx context.Context, req *GetFrequentlyRepliedUsersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/get-frequently-replied-users", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// RecommendationRequest represents the request body for users/recommendation.
type RecommendationRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Recommendation calls /users/recommendation (authenticated).
func (s *Service) Recommendation(ctx context.Context, req *RecommendationRequest) ([]types.UserDetailed, error) {
	var resp []types.UserDetailed
	if err := s.cli.Do(ctx, "/users/recommendation", req, &resp); err != nil {
		return *new([]types.UserDetailed), err
	}
	return resp, nil
}

// PagesRequest represents the request body for users/pages.
type PagesRequest struct {
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// Pages calls /users/pages.
func (s *Service) Pages(ctx context.Context, req *PagesRequest) ([]types.Page, error) {
	var resp []types.Page
	if err := s.cli.Do(ctx, "/users/pages", req, &resp); err != nil {
		return *new([]types.Page), err
	}
	return resp, nil
}

// UsersRequest represents the request body for users.
type UsersRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Sort *string `json:"sort,omitempty"`
	State *string `json:"state,omitempty"`
	Origin *string `json:"origin,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
}

// Users calls /users.
func (s *Service) Users(ctx context.Context, req *UsersRequest) ([]types.UserDetailed, error) {
	var resp []types.UserDetailed
	if err := s.cli.Do(ctx, "/users", req, &resp); err != nil {
		return *new([]types.UserDetailed), err
	}
	return resp, nil
}

// FollowingRequest represents the request body for users/following.
type FollowingRequest struct {
	UserId *types.ID `json:"userId"`
	Username *string `json:"username"`
	Host *string `json:"host"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
}

// Following calls /users/following.
func (s *Service) Following(ctx context.Context, req *FollowingRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/following", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ListsCreateFromPublicRequest represents the request body for users/lists/create-from-public.
type ListsCreateFromPublicRequest struct {
	Name *string `json:"name"`
	ListId *types.ID `json:"listId"`
}

// ListsCreateFromPublic calls /users/lists/create-from-public (authenticated).
func (s *Service) ListsCreateFromPublic(ctx context.Context, req *ListsCreateFromPublicRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/users/lists/create-from-public", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// RelationRequest represents the request body for users/relation.
type RelationRequest struct {
	UserId any `json:"userId"`
}

// Relation calls /users/relation (authenticated).
func (s *Service) Relation(ctx context.Context, req *RelationRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/users/relation", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ClipsRequest represents the request body for users/clips.
type ClipsRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
}

// Clips calls /users/clips.
func (s *Service) Clips(ctx context.Context, req *ClipsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/clips", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// UpdateMemoRequest represents the request body for users/update-memo.
type UpdateMemoRequest struct {
	UserId *types.ID `json:"userId"`
	Memo *string `json:"memo"`
}

// UpdateMemo calls /users/update-memo (authenticated).
func (s *Service) UpdateMemo(ctx context.Context, req *UpdateMemoRequest) error {
	return s.cli.Do(ctx, "/users/update-memo", req, nil)
}

// ListsGetMembershipsRequest represents the request body for users/lists/get-memberships.
type ListsGetMembershipsRequest struct {
	ListId *types.ID `json:"listId"`
	ForPublic *bool `json:"forPublic,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// ListsGetMemberships calls /users/lists/get-memberships.
func (s *Service) ListsGetMemberships(ctx context.Context, req *ListsGetMembershipsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/lists/get-memberships", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ListsUpdateMembershipRequest represents the request body for users/lists/update-membership.
type ListsUpdateMembershipRequest struct {
	ListId *types.ID `json:"listId"`
	UserId *types.ID `json:"userId"`
	WithReplies *bool `json:"withReplies,omitempty"`
}

// ListsUpdateMembership calls /users/lists/update-membership (authenticated).
func (s *Service) ListsUpdateMembership(ctx context.Context, req *ListsUpdateMembershipRequest) error {
	return s.cli.Do(ctx, "/users/lists/update-membership", req, nil)
}

// ListsFavoriteRequest represents the request body for users/lists/favorite.
type ListsFavoriteRequest struct {
	ListId *types.ID `json:"listId"`
}

// ListsFavorite calls /users/lists/favorite (authenticated).
func (s *Service) ListsFavorite(ctx context.Context, req *ListsFavoriteRequest) error {
	return s.cli.Do(ctx, "/users/lists/favorite", req, nil)
}

// ListsPushRequest represents the request body for users/lists/push.
type ListsPushRequest struct {
	ListId *types.ID `json:"listId"`
	UserId *types.ID `json:"userId"`
}

// ListsPush calls /users/lists/push (authenticated).
func (s *Service) ListsPush(ctx context.Context, req *ListsPushRequest) error {
	return s.cli.Do(ctx, "/users/lists/push", req, nil)
}

// ListsShowRequest represents the request body for users/lists/show.
type ListsShowRequest struct {
	ListId *types.ID `json:"listId"`
	ForPublic *bool `json:"forPublic,omitempty"`
}

// ListsShow calls /users/lists/show.
func (s *Service) ListsShow(ctx context.Context, req *ListsShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/users/lists/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// ListsPullRequest represents the request body for users/lists/pull.
type ListsPullRequest struct {
	ListId *types.ID `json:"listId"`
	UserId *types.ID `json:"userId"`
}

// ListsPull calls /users/lists/pull (authenticated).
func (s *Service) ListsPull(ctx context.Context, req *ListsPullRequest) error {
	return s.cli.Do(ctx, "/users/lists/pull", req, nil)
}

// FollowersRequest represents the request body for users/followers.
type FollowersRequest struct {
	UserId *types.ID `json:"userId"`
	Username *string `json:"username"`
	Host *string `json:"host"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Followers calls /users/followers.
func (s *Service) Followers(ctx context.Context, req *FollowersRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/followers", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// AchievementsRequest represents the request body for users/achievements.
type AchievementsRequest struct {
	UserId *types.ID `json:"userId"`
}

// Achievements calls /users/achievements.
func (s *Service) Achievements(ctx context.Context, req *AchievementsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/achievements", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// FlashsRequest represents the request body for users/flashs.
type FlashsRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
}

// Flashs calls /users/flashs.
func (s *Service) Flashs(ctx context.Context, req *FlashsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/flashs", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// GalleryPostsRequest represents the request body for users/gallery/posts.
type GalleryPostsRequest struct {
	UntilDate *int64 `json:"untilDate,omitempty"`
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
}

// GalleryPosts calls /users/gallery/posts.
func (s *Service) GalleryPosts(ctx context.Context, req *GalleryPostsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/gallery/posts", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ListsDeleteRequest represents the request body for users/lists/delete.
type ListsDeleteRequest struct {
	ListId *types.ID `json:"listId"`
}

// ListsDelete calls /users/lists/delete (authenticated).
func (s *Service) ListsDelete(ctx context.Context, req *ListsDeleteRequest) error {
	return s.cli.Do(ctx, "/users/lists/delete", req, nil)
}

// ListsCreateRequest represents the request body for users/lists/create.
type ListsCreateRequest struct {
	Name *string `json:"name"`
}

// ListsCreate calls /users/lists/create (authenticated).
func (s *Service) ListsCreate(ctx context.Context, req *ListsCreateRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/users/lists/create", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// SearchByUsernameAndHostRequest represents the request body for users/search-by-username-and-host.
type SearchByUsernameAndHostRequest struct {
	Username *string `json:"username"`
	Host *string `json:"host"`
	Limit *int64 `json:"limit,omitempty"`
	Detail *bool `json:"detail,omitempty"`
}

// SearchByUsernameAndHost calls /users/search-by-username-and-host.
func (s *Service) SearchByUsernameAndHost(ctx context.Context, req *SearchByUsernameAndHostRequest) ([]types.UserLite, error) {
	var resp []types.UserLite
	if err := s.cli.Do(ctx, "/users/search-by-username-and-host", req, &resp); err != nil {
		return *new([]types.UserLite), err
	}
	return resp, nil
}

// GetFollowingUsersByBirthdayRequest represents the request body for users/get-following-users-by-birthday.
type GetFollowingUsersByBirthdayRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
	Birthday any `json:"birthday"`
}

// GetFollowingUsersByBirthday calls /users/get-following-users-by-birthday (authenticated).
func (s *Service) GetFollowingUsersByBirthday(ctx context.Context, req *GetFollowingUsersByBirthdayRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/get-following-users-by-birthday", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// ListsUnfavoriteRequest represents the request body for users/lists/unfavorite.
type ListsUnfavoriteRequest struct {
	ListId *types.ID `json:"listId"`
}

// ListsUnfavorite calls /users/lists/unfavorite (authenticated).
func (s *Service) ListsUnfavorite(ctx context.Context, req *ListsUnfavoriteRequest) error {
	return s.cli.Do(ctx, "/users/lists/unfavorite", req, nil)
}

// ReactionsRequest represents the request body for users/reactions.
type ReactionsRequest struct {
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	UserId *types.ID `json:"userId"`
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
}

// Reactions calls /users/reactions.
func (s *Service) Reactions(ctx context.Context, req *ReactionsRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/users/reactions", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

