// Code generated by tools/gen/main.go. DO NOT EDIT.

package following

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// UpdateRequest represents the request body for following/update.
type UpdateRequest struct {
	UserId *types.ID `json:"userId"`
	Notify *string `json:"notify,omitempty"`
	WithReplies *bool `json:"withReplies,omitempty"`
}

// Update calls /following/update (authenticated).
func (s *Service) Update(ctx context.Context, req *UpdateRequest) (types.UserLite, error) {
	var resp types.UserLite
	if err := s.cli.Do(ctx, "/following/update", req, &resp); err != nil {
		return *new(types.UserLite), err
	}
	return resp, nil
}

// RequestsSentRequest represents the request body for following/requests/sent.
type RequestsSentRequest struct {
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// RequestsSent calls /following/requests/sent (authenticated).
func (s *Service) RequestsSent(ctx context.Context, req *RequestsSentRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/following/requests/sent", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// UpdateAllRequest represents the request body for following/update-all.
type UpdateAllRequest struct {
	Notify *string `json:"notify,omitempty"`
	WithReplies *bool `json:"withReplies,omitempty"`
}

// UpdateAll calls /following/update-all (authenticated).
func (s *Service) UpdateAll(ctx context.Context, req *UpdateAllRequest) error {
	return s.cli.Do(ctx, "/following/update-all", req, nil)
}

