// Code generated by tools/gen/main.go. DO NOT EDIT.

package renotemute

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides renotemute-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new RenotemuteService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// CreateRequest represents the request body for renote-mute/create.
type CreateRequest struct {
	UserId *types.ID `json:"userId"`
}

// Create calls /renote-mute/create (authenticated).
func (s *Service) Create(ctx context.Context, req *CreateRequest) error {
	return s.cli.Do(ctx, "/renote-mute/create", req, nil)
}

// DeleteRequest represents the request body for renote-mute/delete.
type DeleteRequest struct {
	UserId *types.ID `json:"userId"`
}

// Delete calls /renote-mute/delete (authenticated).
func (s *Service) Delete(ctx context.Context, req *DeleteRequest) error {
	return s.cli.Do(ctx, "/renote-mute/delete", req, nil)
}

// ListRequest represents the request body for renote-mute/list.
type ListRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	SinceId *types.ID `json:"sinceId,omitempty"`
	UntilId *types.ID `json:"untilId,omitempty"`
	SinceDate *int64 `json:"sinceDate,omitempty"`
	UntilDate *int64 `json:"untilDate,omitempty"`
}

// List calls /renote-mute/list (authenticated).
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/renote-mute/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

