// Code generated by tools/gen/main.go. DO NOT EDIT.

package promo

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides promo-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new PromoService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ReadRequest represents the request body for promo/read.
type ReadRequest struct {
	NoteId *types.ID `json:"noteId"`
}

// Read calls /promo/read (authenticated).
func (s *Service) Read(ctx context.Context, req *ReadRequest) error {
	return s.cli.Do(ctx, "/promo/read", req, nil)
}

