// Code generated by tools/gen/main.go. DO NOT EDIT.

package hashtags

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides hashtags-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new HashtagsService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// ListRequest represents the request body for hashtags/list.
type ListRequest struct {
	Limit *int64 `json:"limit,omitempty"`
	AttachedToUserOnly *bool `json:"attachedToUserOnly,omitempty"`
	AttachedToLocalUserOnly *bool `json:"attachedToLocalUserOnly,omitempty"`
	AttachedToRemoteUserOnly *bool `json:"attachedToRemoteUserOnly,omitempty"`
	Sort *string `json:"sort"`
}

// List calls /hashtags/list.
func (s *Service) List(ctx context.Context, req *ListRequest) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/hashtags/list", req, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// Trend calls /hashtags/trend.
func (s *Service) Trend(ctx context.Context) ([]any, error) {
	var resp []any
	if err := s.cli.Do(ctx, "/hashtags/trend", nil, &resp); err != nil {
		return *new([]any), err
	}
	return resp, nil
}

// SearchRequest represents the request body for hashtags/search.
type SearchRequest struct {
	Query *string `json:"query"`
	Offset *int64 `json:"offset,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

// Search calls /hashtags/search.
func (s *Service) Search(ctx context.Context, req *SearchRequest) ([]string, error) {
	var resp []string
	if err := s.cli.Do(ctx, "/hashtags/search", req, &resp); err != nil {
		return *new([]string), err
	}
	return resp, nil
}

// ShowRequest represents the request body for hashtags/show.
type ShowRequest struct {
	Tag *string `json:"tag"`
}

// Show calls /hashtags/show.
func (s *Service) Show(ctx context.Context, req *ShowRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/hashtags/show", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

// UsersRequest represents the request body for hashtags/users.
type UsersRequest struct {
	Offset *int64 `json:"offset,omitempty"`
	Sort *string `json:"sort"`
	State *string `json:"state,omitempty"`
	Origin *string `json:"origin,omitempty"`
	Tag *string `json:"tag"`
	Limit *int64 `json:"limit,omitempty"`
}

// Users calls /hashtags/users.
func (s *Service) Users(ctx context.Context, req *UsersRequest) ([]types.UserDetailed, error) {
	var resp []types.UserDetailed
	if err := s.cli.Do(ctx, "/hashtags/users", req, &resp); err != nil {
		return *new([]types.UserDetailed), err
	}
	return resp, nil
}

