// Code generated by tools/gen/main.go. DO NOT EDIT.

package emoji

import (
	"context"
	"github.com/sysnote8main/migo/types"
)

// Service provides emoji-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new EmojiService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// EmojiRequest represents the request body for emoji.
type EmojiRequest struct {
	Name *string `json:"name"`
}

// Emoji calls /emoji.
func (s *Service) Emoji(ctx context.Context, req *EmojiRequest) (types.EmojiDetailed, error) {
	var resp types.EmojiDetailed
	if err := s.cli.Do(ctx, "/emoji", req, &resp); err != nil {
		return *new(types.EmojiDetailed), err
	}
	return resp, nil
}

