// Code generated by tools/gen/main.go. DO NOT EDIT.

package emailaddress

import "context"

// Service provides emailaddress-related API operations.
type Service struct {
	cli doer
}

type doer interface {
	Do(ctx context.Context, path string, req, resp any) error
}

// NewService creates a new EmailaddressService.
func NewService(cli doer) *Service {
	return &Service{cli: cli}
}

// AvailableRequest represents the request body for email-address/available.
type AvailableRequest struct {
	EmailAddress *string `json:"emailAddress"`
}

// Available calls /email-address/available.
func (s *Service) Available(ctx context.Context, req *AvailableRequest) (any, error) {
	var resp any
	if err := s.cli.Do(ctx, "/email-address/available", req, &resp); err != nil {
		return *new(any), err
	}
	return resp, nil
}

